$axure.loadCurrentPage({
  "url":"按钮.html",
  "generationDate":new Date(1414911756993.31),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f8cfb5b275634ce09d64e4301f465c38",
    "type":"Axure:Page",
    "name":"按钮",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"021d0ad69b80401b8e71322b6c0499b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":80},
            "size":{
              "width":624,
              "height":90},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"186dc74aa0a64d70bed547ad55d10338",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":80},
                "size":{
                  "width":624,
                  "height":90},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/按钮/u0.png"}},
{
          "id":"70943ab04dcd4a418a062f03392c671e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "verticalAlignment":"middle",
            "location":{
              "x":346,
              "y":104},
            "size":{
              "width":73,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ef1523b1fef40f5a0cfac5c9b3e72d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "verticalAlignment":"middle",
                "location":{
                  "x":346,
                  "y":104},
                "size":{
                  "width":73,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3b10ebe90b7343aaafcade8d2a1015a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":70,
              "y":190},
            "size":{
              "width":624,
              "height":90},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d45bd198064c4ae6aa7ab20cb3974ddc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":70,
                  "y":190},
                "size":{
                  "width":624,
                  "height":90},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/按钮/u4.png"}},
{
          "id":"3ecf52e4869d491aa7bcde49ec86ead3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":346,
              "y":214},
            "size":{
              "width":73,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5aa72f1284544abfab1f7fe8f9c39527",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":346,
                  "y":214},
                "size":{
                  "width":73,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9570145760d140aab7a2d10dbcabc04d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":310},
            "size":{
              "width":624,
              "height":90},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f27230fa73a444f38c519c37bf257cf5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":310},
                "size":{
                  "width":624,
                  "height":90},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFE6E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/按钮/u8.png"}},
{
          "id":"15c2aadbc4c1409d8182f3dd624c25fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF46E49,
              "opacity":1},
            "location":{
              "x":346,
              "y":334},
            "size":{
              "width":73,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bde5fa2887bc40719d0ef6c7a415a40f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49,
                  "opacity":1},
                "location":{
                  "x":346,
                  "y":334},
                "size":{
                  "width":73,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48fd4c92edb24e9c8496e47fbdcff205",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF46E49,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFE6E49},
            "location":{
              "x":70,
              "y":420},
            "size":{
              "width":624,
              "height":90},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fcfe32263b44900bad2e377b851ac37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFE6E49},
                "location":{
                  "x":70,
                  "y":420},
                "size":{
                  "width":624,
                  "height":90},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFE6E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/按钮/u12.png"}},
{
          "id":"8e7af07c405845d4b486501df4ea41fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":346,
              "y":444},
            "size":{
              "width":73,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e522107afa4246128aeb9636d6bb81a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":346,
                  "y":444},
                "size":{
                  "width":73,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "021d0ad69b80401b8e71322b6c0499b2":{
      "scriptId":"u0"},
    "186dc74aa0a64d70bed547ad55d10338":{
      "scriptId":"u1"},
    "70943ab04dcd4a418a062f03392c671e":{
      "scriptId":"u2"},
    "6ef1523b1fef40f5a0cfac5c9b3e72d0":{
      "scriptId":"u3"},
    "3b10ebe90b7343aaafcade8d2a1015a7":{
      "scriptId":"u4"},
    "d45bd198064c4ae6aa7ab20cb3974ddc":{
      "scriptId":"u5"},
    "3ecf52e4869d491aa7bcde49ec86ead3":{
      "scriptId":"u6"},
    "5aa72f1284544abfab1f7fe8f9c39527":{
      "scriptId":"u7"},
    "9570145760d140aab7a2d10dbcabc04d":{
      "scriptId":"u8"},
    "f27230fa73a444f38c519c37bf257cf5":{
      "scriptId":"u9"},
    "15c2aadbc4c1409d8182f3dd624c25fe":{
      "scriptId":"u10"},
    "bde5fa2887bc40719d0ef6c7a415a40f":{
      "scriptId":"u11"},
    "48fd4c92edb24e9c8496e47fbdcff205":{
      "scriptId":"u12"},
    "7fcfe32263b44900bad2e377b851ac37":{
      "scriptId":"u13"},
    "8e7af07c405845d4b486501df4ea41fa":{
      "scriptId":"u14"},
    "e522107afa4246128aeb9636d6bb81a7":{
      "scriptId":"u15"}}});