$axure.loadCurrentPage({
  "url":"忘记密码_-_2.html",
  "generationDate":new Date(1414911758380.27),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b4e216d666c14d85a0bc358e524725a8",
    "type":"Axure:Page",
    "name":"忘记密码 - 2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"22b116515df145a9bb9f9703a21259c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFCFCFC},
            "size":{
              "width":720,
              "height":1280},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFCFCFC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d908127a2834d1d99621934c5ddb7bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFCFCFC},
                "size":{
                  "width":720,
                  "height":1280},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFCFCFC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u0.png"}},
{
          "id":"7d45b61e03d4452098ed1c583158b942",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":0,
              "y":1182},
            "size":{
              "width":720,
              "height":98},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9581bd2fff1f42a493692b95bce3839b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":0,
                  "y":1182},
                "size":{
                  "width":720,
                  "height":98},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u2.png"}},
{
          "id":"4551cf8b923c4bf4a7ae1c44a10ca4b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":137,
              "y":1206},
            "size":{
              "width":42,
              "height":50},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA2A2A2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9179dbf5076c4612ba2e47ab0bff5e80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":137,
                  "y":1206},
                "size":{
                  "width":42,
                  "height":50},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA2A2A2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u4.png"}},
{
          "id":"c3b4c74a010e4ac4916a798b34b24ca3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":335,
              "y":1206},
            "size":{
              "width":50,
              "height":50},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA2A2A2},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d60d70dd49214356ad2867c526de9b75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":335,
                  "y":1206},
                "size":{
                  "width":50,
                  "height":50},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA2A2A2},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u6.png"}},
{
          "id":"bcdbb7acd1bd410bb835fe690ee364dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":541,
              "y":1209},
            "size":{
              "width":44,
              "height":44},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA2A2A2},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b125ca5e55a4c249419a9ba3c142cec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":541,
                  "y":1209},
                "size":{
                  "width":44,
                  "height":44},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA2A2A2},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u8.png"}},
{
          "id":"1f9221fb8150467a94e4d2d0a19ed051",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000}]},
            "size":{
              "width":720,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFB3B3B3}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5dfa3ca255d64cab96fa998a7478579b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000}]},
                "size":{
                  "width":720,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFB3B3B3}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u10.png"}},
{
          "id":"99ac9947f7194409922b45a2bab04c76",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Roboto Thin', 'Roboto'",
            "fontWeight":"250",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF8F8FA,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000}]},
            "location":{
              "x":642,
              "y":10},
            "size":{
              "width":51,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee1c951aa7df40af90ff99d7ed963532",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Thin', 'Roboto'",
                "fontWeight":"250",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF8F8FA,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000}]},
                "location":{
                  "x":642,
                  "y":10},
                "size":{
                  "width":51,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u12.png"}},
{
          "id":"1fb47d8fbc7e43c389e0a7d92426e142",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000}]},
            "location":{
              "x":604,
              "y":23},
            "size":{
              "width":18,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b45c60df09b84547864116b1ebd6e9b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000}]},
                "location":{
                  "x":604,
                  "y":23},
                "size":{
                  "width":18,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/忘记密码/u14.png"}},
{
          "id":"f578a0ed37a844e9b4d39bb362e5850c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000}]},
            "location":{
              "x":604,
              "y":11},
            "size":{
              "width":18,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4af49884be30448ab34342c5ed019701",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000}]},
                "location":{
                  "x":604,
                  "y":11},
                "size":{
                  "width":18,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/忘记密码/u14.png"}},
{
          "id":"afddb820b1764c5dafc324beca336528",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000}]},
            "location":{
              "x":608,
              "y":9},
            "size":{
              "width":8,
              "height":2},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC6C6C6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7b88e17638246e98fea9f60b6157bfe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000}]},
                "location":{
                  "x":608,
                  "y":9},
                "size":{
                  "width":8,
                  "height":2},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC6C6C6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u18.png"}},
{
          "id":"9b7c4a6f5a9a495b809d98cc534b5ddf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":0,
              "y":48},
            "size":{
              "width":720,
              "height":100},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42d9955cf8ff414b942280d0be003b7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":0,
                  "y":48},
                "size":{
                  "width":720,
                  "height":100},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFE6E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航栏/u0.png"}},
{
          "id":"c717c81f60f94085a64f7bd07243ddcc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":100,
              "y":77},
            "size":{
              "width":145,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ad9ba6008164736b8c55604eb30ba97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":100,
                  "y":77},
                "size":{
                  "width":145,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7fd104c1386944cbadb4c6a25b267e56",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":75},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3300c3a8bd7143eba891ca111e563ae6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":75},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/忘记密码/u24.png"}},
{
          "id":"2ef193234dc1430fb715437c48901a31",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":645,
              "y":73},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b922707bd0ec48599a54b4e8fc26fd5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":645,
                  "y":73},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/忘记密码/u26.png"}},
{
          "id":"c2daeb8d64044e399ab82021215820b3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":239},
            "size":{
              "width":624,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u0_line.png"}},
{
          "id":"c7232e2b7de74d0da83ca51d19dfb5f8",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":237},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u1_line.png"}},
{
          "id":"1f095e2983074364a3a90f27411b148a",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":666,
              "y":237},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u1_line.png"}},
{
          "id":"7a61e744d20648efb42a53bd632c1758",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":64,
              "y":203},
            "size":{
              "width":191,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27e749204c404ef0bd6a75f7ca07f826",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":64,
                  "y":203},
                "size":{
                  "width":191,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e1a2446df0c4e24ac17a98935a27c33",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":330},
            "size":{
              "width":624,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u3_line.png"}},
{
          "id":"07f987d72bc145b3b7da98c57187328a",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":328},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u4_line.png"}},
{
          "id":"5c3b3f712e974ab492b94dfb9fc5eeb3",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":666,
              "y":328},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u4_line.png"}},
{
          "id":"5c2dd7d4139a4b348a13cc45e0d9a5ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":64,
              "y":294},
            "size":{
              "width":141,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68eff78656304fbdab621ac1a1dce562",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":64,
                  "y":294},
                "size":{
                  "width":141,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEAEAEA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad680f799fa44e759b5ee4283d5a569a",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":237},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u1_line.png"}},
{
          "id":"6faee06bf0a943e389dede145103de6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0BAA9E,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xBAA9E},
            "location":{
              "x":460,
              "y":203},
            "size":{
              "width":197,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5948a1897c234a8f9d466bb35d73c75b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0BAA9E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xBAA9E},
                "location":{
                  "x":460,
                  "y":203},
                "size":{
                  "width":197,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e661823d2d04cd58c8db4122db5174e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF2A2A2A},
            "location":{
              "x":75,
              "y":1000},
            "size":{
              "width":570,
              "height":70},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":10,
              "color":{
                "r":153,
                "g":153,
                "b":153,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2aa2f3172e9149848619dbdc8ef72415",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF2A2A2A},
                "location":{
                  "x":75,
                  "y":1000},
                "size":{
                  "width":570,
                  "height":70},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":10,
                  "color":{
                    "r":153,
                    "g":153,
                    "b":153,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提示框/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "22b116515df145a9bb9f9703a21259c8":{
      "scriptId":"u0"},
    "1d908127a2834d1d99621934c5ddb7bf":{
      "scriptId":"u1"},
    "7d45b61e03d4452098ed1c583158b942":{
      "scriptId":"u2"},
    "9581bd2fff1f42a493692b95bce3839b":{
      "scriptId":"u3"},
    "4551cf8b923c4bf4a7ae1c44a10ca4b2":{
      "scriptId":"u4"},
    "9179dbf5076c4612ba2e47ab0bff5e80":{
      "scriptId":"u5"},
    "c3b4c74a010e4ac4916a798b34b24ca3":{
      "scriptId":"u6"},
    "d60d70dd49214356ad2867c526de9b75":{
      "scriptId":"u7"},
    "bcdbb7acd1bd410bb835fe690ee364dc":{
      "scriptId":"u8"},
    "4b125ca5e55a4c249419a9ba3c142cec":{
      "scriptId":"u9"},
    "1f9221fb8150467a94e4d2d0a19ed051":{
      "scriptId":"u10"},
    "5dfa3ca255d64cab96fa998a7478579b":{
      "scriptId":"u11"},
    "99ac9947f7194409922b45a2bab04c76":{
      "scriptId":"u12"},
    "ee1c951aa7df40af90ff99d7ed963532":{
      "scriptId":"u13"},
    "1fb47d8fbc7e43c389e0a7d92426e142":{
      "scriptId":"u14"},
    "b45c60df09b84547864116b1ebd6e9b7":{
      "scriptId":"u15"},
    "f578a0ed37a844e9b4d39bb362e5850c":{
      "scriptId":"u16"},
    "4af49884be30448ab34342c5ed019701":{
      "scriptId":"u17"},
    "afddb820b1764c5dafc324beca336528":{
      "scriptId":"u18"},
    "e7b88e17638246e98fea9f60b6157bfe":{
      "scriptId":"u19"},
    "9b7c4a6f5a9a495b809d98cc534b5ddf":{
      "scriptId":"u20"},
    "42d9955cf8ff414b942280d0be003b7c":{
      "scriptId":"u21"},
    "c717c81f60f94085a64f7bd07243ddcc":{
      "scriptId":"u22"},
    "1ad9ba6008164736b8c55604eb30ba97":{
      "scriptId":"u23"},
    "7fd104c1386944cbadb4c6a25b267e56":{
      "scriptId":"u24"},
    "3300c3a8bd7143eba891ca111e563ae6":{
      "scriptId":"u25"},
    "2ef193234dc1430fb715437c48901a31":{
      "scriptId":"u26"},
    "b922707bd0ec48599a54b4e8fc26fd5a":{
      "scriptId":"u27"},
    "c2daeb8d64044e399ab82021215820b3":{
      "scriptId":"u28"},
    "c7232e2b7de74d0da83ca51d19dfb5f8":{
      "scriptId":"u29"},
    "1f095e2983074364a3a90f27411b148a":{
      "scriptId":"u30"},
    "7a61e744d20648efb42a53bd632c1758":{
      "scriptId":"u31"},
    "27e749204c404ef0bd6a75f7ca07f826":{
      "scriptId":"u32"},
    "8e1a2446df0c4e24ac17a98935a27c33":{
      "scriptId":"u33"},
    "07f987d72bc145b3b7da98c57187328a":{
      "scriptId":"u34"},
    "5c3b3f712e974ab492b94dfb9fc5eeb3":{
      "scriptId":"u35"},
    "5c2dd7d4139a4b348a13cc45e0d9a5ae":{
      "scriptId":"u36"},
    "68eff78656304fbdab621ac1a1dce562":{
      "scriptId":"u37"},
    "ad680f799fa44e759b5ee4283d5a569a":{
      "scriptId":"u38"},
    "6faee06bf0a943e389dede145103de6f":{
      "scriptId":"u39"},
    "5948a1897c234a8f9d466bb35d73c75b":{
      "scriptId":"u40"},
    "0e661823d2d04cd58c8db4122db5174e":{
      "scriptId":"u41"},
    "2aa2f3172e9149848619dbdc8ef72415":{
      "scriptId":"u42"}}});