$axure.loadCurrentPage({
  "url":"引导页面_-_3.html",
  "generationDate":new Date(1414911756846.23),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3d2f5ae641504633a7cf523bb03fbfb8",
    "type":"Axure:Page",
    "name":"引导页面 - 3",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dc48dab558ba465cad81c2b224415bfc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":720,
              "height":1280}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aff8fd16d7f2430c9eef8e4b4e54ba68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":720,
                  "height":1280}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/引导页面_-_3/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "dc48dab558ba465cad81c2b224415bfc":{
      "scriptId":"u0"},
    "aff8fd16d7f2430c9eef8e4b4e54ba68":{
      "scriptId":"u1"}}});