$axure.loadCurrentPage({
  "url":"登录界面.html",
  "generationDate":new Date(1414911757352.56),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"da4173f38c1b40dc99fb60ac749ada81",
    "type":"Axure:Page",
    "name":"登录界面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"aa17a17b5f154a979b7e31ad0e3fb070",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFCFCFC},
            "size":{
              "width":720,
              "height":1280},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFCFCFC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a9078f0dfec48c39f6f25c4eb3864ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFCFCFC},
                "size":{
                  "width":720,
                  "height":1280},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFCFCFC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u0.png"}},
{
          "id":"eab9cb42951f4edeb9186e107bd31d74",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":0,
              "y":1182},
            "size":{
              "width":720,
              "height":98},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8897a85eef94d9cac4437a148d5588f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":0,
                  "y":1182},
                "size":{
                  "width":720,
                  "height":98},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u2.png"}},
{
          "id":"3677b4caa9b040a4bd38596e0e7a5e3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":137,
              "y":1206},
            "size":{
              "width":42,
              "height":50},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA2A2A2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c40fb0e5ead41eaa8aa05b45f4485a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":137,
                  "y":1206},
                "size":{
                  "width":42,
                  "height":50},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA2A2A2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u4.png"}},
{
          "id":"6294f7140aef4043b3c903a25c2b7f1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":335,
              "y":1206},
            "size":{
              "width":50,
              "height":50},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA2A2A2},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6018696f7f249fabb296ef4e95d4f5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":335,
                  "y":1206},
                "size":{
                  "width":50,
                  "height":50},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA2A2A2},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u6.png"}},
{
          "id":"48cfd1cf56a14a89a101b6bf89958f91",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":541,
              "y":1209},
            "size":{
              "width":44,
              "height":44},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA2A2A2},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffb74f03de414447a40562eb75ee471b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":541,
                  "y":1209},
                "size":{
                  "width":44,
                  "height":44},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA2A2A2},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u8.png"}},
{
          "id":"1595d844b6ff4a028d317cf0deae8add",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "size":{
              "width":720,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15c4b27551ae4cd2978e8cb2af615ada",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "size":{
                  "width":720,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录界面/u10.png"}},
{
          "id":"65770ecc11384363a3829d981bdfa6a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Roboto Thin', 'Roboto'",
            "fontWeight":"250",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF8F8FA,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":642,
              "y":10},
            "size":{
              "width":51,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81beea7e483d434ea6a9d395209eb659",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Thin', 'Roboto'",
                "fontWeight":"250",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF8F8FA,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":642,
                  "y":10},
                "size":{
                  "width":51,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u12.png"}},
{
          "id":"1982842c38d54c4b91b6115482d94e4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":604,
              "y":23},
            "size":{
              "width":18,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF8F8FA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ab4a09abd1141f8ace439c126977d12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":604,
                  "y":23},
                "size":{
                  "width":18,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF8F8FA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u14.png"}},
{
          "id":"153d48e7bd364ae5bded863fbd4b6f31",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":604,
              "y":11},
            "size":{
              "width":18,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC6C6C6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b524dce303ee479ba8d4cfb4e676a47f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":604,
                  "y":11},
                "size":{
                  "width":18,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC6C6C6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u16.png"}},
{
          "id":"83e25bbba2294fcbb42ee240c57bbfa5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":608,
              "y":9},
            "size":{
              "width":8,
              "height":2},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC6C6C6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c10ecdd115de43c1b6b8fca2a1100fe7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":608,
                  "y":9},
                "size":{
                  "width":8,
                  "height":2},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC6C6C6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u18.png"}},
{
          "id":"390e053449544df9bf52a785f0847103",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":480},
            "size":{
              "width":624,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u0_line.png"}},
{
          "id":"4f4b3bc2a9874007b695051868f3821c",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":478},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u1_line.png"}},
{
          "id":"c77278f2a34041fe92edc452bab2f255",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":666,
              "y":478},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u1_line.png"}},
{
          "id":"e75d93f16e5241d7a91e21744f7948be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":116,
              "y":444},
            "size":{
              "width":85,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b5b712748664b85aaa8baf530fd4d8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":116,
                  "y":444},
                "size":{
                  "width":85,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a7f12620348457d93373cf43128ff50",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA,
              "opacity":1},
            "location":{
              "x":208,
              "y":444},
            "size":{
              "width":225,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca028ee954b84863bf2fe65b7f42dd1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFEAEAEA,
                  "opacity":1},
                "location":{
                  "x":208,
                  "y":444},
                "size":{
                  "width":225,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98ae124c4be04f4ca940b6844bb9806a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":590},
            "size":{
              "width":624,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u3_line.png"}},
{
          "id":"2f2571a94a0a4abd893d540c64c758d6",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":588},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u4_line.png"}},
{
          "id":"42e5319e0974467d9fda345e85688061",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":666,
              "y":588},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u4_line.png"}},
{
          "id":"0fe0614f24374fb8b621e54b2ab5524e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":116,
              "y":554},
            "size":{
              "width":73,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c19b377829941729126018dbf62789b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":116,
                  "y":554},
                "size":{
                  "width":73,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEAEAEA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ab5b78941454823ada32632ad031aa1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA,
              "opacity":1},
            "location":{
              "x":208,
              "y":554},
            "size":{
              "width":225,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7efc0d9b962546dfa1491410b8d9eb1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFEAEAEA,
                  "opacity":1},
                "location":{
                  "x":208,
                  "y":554},
                "size":{
                  "width":225,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEAEAEA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd73f9a5cbd54694bcb33dcf0d8c80dc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":441},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af28f5df0b554f5bac175954dc089653",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":441},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录界面/u34.png"}},
{
          "id":"c6d6caa72b704733bd60c961c18b02bd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":551},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"853f1b4ad6724f12a7bfc6ccaa5b73b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":551},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录界面/u36.png"}},
{
          "id":"6540a7e7773941bd8becf4667f2224ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"72px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF46E49,
              "opacity":1},
            "location":{
              "x":152,
              "y":209},
            "size":{
              "width":289,
              "height":83},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5627865ca42845629b87260509350937",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"72px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49,
                  "opacity":1},
                "location":{
                  "x":152,
                  "y":209},
                "size":{
                  "width":289,
                  "height":83},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFE6E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4076327ee32c49658b9d3761542e06b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF46E49,
              "opacity":1},
            "location":{
              "x":258,
              "y":302},
            "size":{
              "width":309,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f11d63d6b015468f9abe7b7023ef175d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49,
                  "opacity":1},
                "location":{
                  "x":258,
                  "y":302},
                "size":{
                  "width":309,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFE6E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"171a2204994444918312b41901b6c9e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF46E49,
              "opacity":1},
            "location":{
              "x":559,
              "y":607},
            "size":{
              "width":113,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8225f8d5177544be992058d5075bdc91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49,
                  "opacity":1},
                "location":{
                  "x":559,
                  "y":607},
                "size":{
                  "width":113,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a4ce5c81c38e4a95808389150f06f85e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":700},
            "size":{
              "width":624,
              "height":90},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec0924f1578d4ebab5a90d9b0f45a9e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":700},
                "size":{
                  "width":624,
                  "height":90},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFE6E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/按钮/u8.png"}},
{
          "id":"73130249f40846269f21768f32841865",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF46E49,
              "opacity":1},
            "location":{
              "x":320,
              "y":724},
            "size":{
              "width":73,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3889df8b2394ce0b810ad8ac04deec3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49,
                  "opacity":1},
                "location":{
                  "x":320,
                  "y":724},
                "size":{
                  "width":73,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29d27b349a6d4baa98942cf3007e17ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":220,
              "y":807},
            "size":{
              "width":281,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fd6ce09a8ea44be9b32524a1a56bee1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":220,
                  "y":807},
                "size":{
                  "width":281,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"111d1e331273412bb17ee4e5fc6af61b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":418,
              "y":992},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a4f6f8a65964c20b970ec95fabf6a4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":418,
                  "y":992},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录界面/u50.png"}},
{
          "id":"3c9f1271b7aa4051a47e6a4982c1a2f0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":930},
            "size":{
              "width":720,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录界面/u52_line.png"}},
{
          "id":"583497cf917b4f2ca1369fb39dbecc87",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFCFCFC},
            "location":{
              "x":262,
              "y":918},
            "size":{
              "width":197,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"055e7088258b463dbf75e8f6b288b695",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFEAEAEA,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFCFCFC},
                "location":{
                  "x":262,
                  "y":918},
                "size":{
                  "width":197,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录界面/u53.png"}},
{
          "id":"6f4e6bf7b855484aa4da3954fd349e89",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":152,
              "y":991},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"777f77d9bf7a453ebd3591966bc4c239",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":152,
                  "y":991},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录界面/u55.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "aa17a17b5f154a979b7e31ad0e3fb070":{
      "scriptId":"u0"},
    "3a9078f0dfec48c39f6f25c4eb3864ff":{
      "scriptId":"u1"},
    "eab9cb42951f4edeb9186e107bd31d74":{
      "scriptId":"u2"},
    "a8897a85eef94d9cac4437a148d5588f":{
      "scriptId":"u3"},
    "3677b4caa9b040a4bd38596e0e7a5e3d":{
      "scriptId":"u4"},
    "1c40fb0e5ead41eaa8aa05b45f4485a1":{
      "scriptId":"u5"},
    "6294f7140aef4043b3c903a25c2b7f1e":{
      "scriptId":"u6"},
    "a6018696f7f249fabb296ef4e95d4f5b":{
      "scriptId":"u7"},
    "48cfd1cf56a14a89a101b6bf89958f91":{
      "scriptId":"u8"},
    "ffb74f03de414447a40562eb75ee471b":{
      "scriptId":"u9"},
    "1595d844b6ff4a028d317cf0deae8add":{
      "scriptId":"u10"},
    "15c4b27551ae4cd2978e8cb2af615ada":{
      "scriptId":"u11"},
    "65770ecc11384363a3829d981bdfa6a6":{
      "scriptId":"u12"},
    "81beea7e483d434ea6a9d395209eb659":{
      "scriptId":"u13"},
    "1982842c38d54c4b91b6115482d94e4d":{
      "scriptId":"u14"},
    "2ab4a09abd1141f8ace439c126977d12":{
      "scriptId":"u15"},
    "153d48e7bd364ae5bded863fbd4b6f31":{
      "scriptId":"u16"},
    "b524dce303ee479ba8d4cfb4e676a47f":{
      "scriptId":"u17"},
    "83e25bbba2294fcbb42ee240c57bbfa5":{
      "scriptId":"u18"},
    "c10ecdd115de43c1b6b8fca2a1100fe7":{
      "scriptId":"u19"},
    "390e053449544df9bf52a785f0847103":{
      "scriptId":"u20"},
    "4f4b3bc2a9874007b695051868f3821c":{
      "scriptId":"u21"},
    "c77278f2a34041fe92edc452bab2f255":{
      "scriptId":"u22"},
    "e75d93f16e5241d7a91e21744f7948be":{
      "scriptId":"u23"},
    "3b5b712748664b85aaa8baf530fd4d8a":{
      "scriptId":"u24"},
    "8a7f12620348457d93373cf43128ff50":{
      "scriptId":"u25"},
    "ca028ee954b84863bf2fe65b7f42dd1b":{
      "scriptId":"u26"},
    "98ae124c4be04f4ca940b6844bb9806a":{
      "scriptId":"u27"},
    "2f2571a94a0a4abd893d540c64c758d6":{
      "scriptId":"u28"},
    "42e5319e0974467d9fda345e85688061":{
      "scriptId":"u29"},
    "0fe0614f24374fb8b621e54b2ab5524e":{
      "scriptId":"u30"},
    "6c19b377829941729126018dbf62789b":{
      "scriptId":"u31"},
    "9ab5b78941454823ada32632ad031aa1":{
      "scriptId":"u32"},
    "7efc0d9b962546dfa1491410b8d9eb1a":{
      "scriptId":"u33"},
    "dd73f9a5cbd54694bcb33dcf0d8c80dc":{
      "scriptId":"u34"},
    "af28f5df0b554f5bac175954dc089653":{
      "scriptId":"u35"},
    "c6d6caa72b704733bd60c961c18b02bd":{
      "scriptId":"u36"},
    "853f1b4ad6724f12a7bfc6ccaa5b73b3":{
      "scriptId":"u37"},
    "6540a7e7773941bd8becf4667f2224ab":{
      "scriptId":"u38"},
    "5627865ca42845629b87260509350937":{
      "scriptId":"u39"},
    "4076327ee32c49658b9d3761542e06b3":{
      "scriptId":"u40"},
    "f11d63d6b015468f9abe7b7023ef175d":{
      "scriptId":"u41"},
    "171a2204994444918312b41901b6c9e2":{
      "scriptId":"u42"},
    "8225f8d5177544be992058d5075bdc91":{
      "scriptId":"u43"},
    "a4ce5c81c38e4a95808389150f06f85e":{
      "scriptId":"u44"},
    "ec0924f1578d4ebab5a90d9b0f45a9e7":{
      "scriptId":"u45"},
    "73130249f40846269f21768f32841865":{
      "scriptId":"u46"},
    "f3889df8b2394ce0b810ad8ac04deec3":{
      "scriptId":"u47"},
    "29d27b349a6d4baa98942cf3007e17ef":{
      "scriptId":"u48"},
    "7fd6ce09a8ea44be9b32524a1a56bee1":{
      "scriptId":"u49"},
    "111d1e331273412bb17ee4e5fc6af61b":{
      "scriptId":"u50"},
    "5a4f6f8a65964c20b970ec95fabf6a4c":{
      "scriptId":"u51"},
    "3c9f1271b7aa4051a47e6a4982c1a2f0":{
      "scriptId":"u52"},
    "583497cf917b4f2ca1369fb39dbecc87":{
      "scriptId":"u53"},
    "055e7088258b463dbf75e8f6b288b695":{
      "scriptId":"u54"},
    "6f4e6bf7b855484aa4da3954fd349e89":{
      "scriptId":"u55"},
    "777f77d9bf7a453ebd3591966bc4c239":{
      "scriptId":"u56"}}});