$axure.loadCurrentPage({
  "url":"登录界面_-_4.html",
  "generationDate":new Date(1414911758011.06),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bcb2224dd3f946b2aef1b0e4278d3be2",
    "type":"Axure:Page",
    "name":"登录界面 - 4",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"35e6af43aa284b25b521cdbc88d23745",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFCFCFC},
            "size":{
              "width":720,
              "height":1280},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFCFCFC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba67001c13ad4a449d6209d8f5a998cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFCFCFC},
                "size":{
                  "width":720,
                  "height":1280},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFCFCFC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u0.png"}},
{
          "id":"bf135e5ee22a4e49b70c0c53fbd6159b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":0,
              "y":1182},
            "size":{
              "width":720,
              "height":98},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1aa5c37076e4f1ab652663218946542",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":0,
                  "y":1182},
                "size":{
                  "width":720,
                  "height":98},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u2.png"}},
{
          "id":"9e1b29d343d640d9b913022fb49d35e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":137,
              "y":1206},
            "size":{
              "width":42,
              "height":50},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA2A2A2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aed8f8f3f4cd447d877f33dfae7cb401",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":137,
                  "y":1206},
                "size":{
                  "width":42,
                  "height":50},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA2A2A2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u4.png"}},
{
          "id":"b98af60fe3c84de5a8c4a18edf9845cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":335,
              "y":1206},
            "size":{
              "width":50,
              "height":50},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA2A2A2},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2227c4debe0e4b45901594a28fd4d49e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":335,
                  "y":1206},
                "size":{
                  "width":50,
                  "height":50},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA2A2A2},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u6.png"}},
{
          "id":"7bd31098f83748ed9d18100c2cc80700",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":541,
              "y":1209},
            "size":{
              "width":44,
              "height":44},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA2A2A2},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3aad4b310d4e49a0b294a9b4094524b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":541,
                  "y":1209},
                "size":{
                  "width":44,
                  "height":44},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA2A2A2},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u8.png"}},
{
          "id":"37d5304df626423fb0ef9602d143fa23",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "size":{
              "width":720,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42527769f9ec44ee895d0e5a2b31677e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "size":{
                  "width":720,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录界面/u10.png"}},
{
          "id":"264c5e3452204598b2a688078adcf74b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Roboto Thin', 'Roboto'",
            "fontWeight":"250",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF8F8FA,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":642,
              "y":10},
            "size":{
              "width":51,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49386d7881ed406285667c400c45d333",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Thin', 'Roboto'",
                "fontWeight":"250",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF8F8FA,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":642,
                  "y":10},
                "size":{
                  "width":51,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u12.png"}},
{
          "id":"b4d7c6f06a4f403fb56370813e49adcf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":604,
              "y":23},
            "size":{
              "width":18,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF8F8FA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c1808c487534e58a51908d6d02b30fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":604,
                  "y":23},
                "size":{
                  "width":18,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF8F8FA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u14.png"}},
{
          "id":"56783ffe90a347d184f8af7a06b2214f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":604,
              "y":11},
            "size":{
              "width":18,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC6C6C6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0bedb5f74574c66a55ba6f6bcdd7748",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":604,
                  "y":11},
                "size":{
                  "width":18,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC6C6C6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u16.png"}},
{
          "id":"d4801bb22e6d4631929c2df2443f09ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":608,
              "y":9},
            "size":{
              "width":8,
              "height":2},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC6C6C6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f514effade7647babd042b7b2dd1c0ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":608,
                  "y":9},
                "size":{
                  "width":8,
                  "height":2},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC6C6C6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u18.png"}},
{
          "id":"965ca0ddd0ca420f9bddb491765d7ebb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":480},
            "size":{
              "width":624,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u3_line.png"}},
{
          "id":"4597da53bfe2476eae9aa445fd28e772",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":478},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u4_line.png"}},
{
          "id":"47821d7ec5b4491f8410c0b841d9ac39",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":666,
              "y":478},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u4_line.png"}},
{
          "id":"9e49286c0085422ab46387af3e96d710",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":116,
              "y":444},
            "size":{
              "width":85,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c64b59e9e664d0db5903e13b77b0250",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":116,
                  "y":444},
                "size":{
                  "width":85,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34f7efbb71c74e4b9972073effcd7a6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":208,
              "y":444},
            "size":{
              "width":262,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26e6f7a25644471285c81dd3668a0e91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":208,
                  "y":444},
                "size":{
                  "width":262,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e552d1f784bb4789a1a4eaf50fbc7383",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":590},
            "size":{
              "width":624,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u0_line.png"}},
{
          "id":"50326a4a9f074869ad0781dd5f389f5b",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":588},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u1_line.png"}},
{
          "id":"eb95e745e7eb40d993cb4012bd88aff7",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":666,
              "y":588},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u1_line.png"}},
{
          "id":"8081d4c2663d48daafbdc98c4b5c2aca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":116,
              "y":554},
            "size":{
              "width":73,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"924ecee06f6d4015b551e18db3950f19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":116,
                  "y":554},
                "size":{
                  "width":73,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEAEAEA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92c22236e477476fa85682ee6fb11821",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":441},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21b181b256884baea799727c656949d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":441},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录界面/u34.png"}},
{
          "id":"fdf49fbbd7f64cadb2776b69fb666453",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":551},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21a90ed6af164fbdab38f0576a13ffb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":551},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录界面/u36.png"}},
{
          "id":"f7aadc470d7c4b468a131e43f0de8f49",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"72px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF46E49,
              "opacity":1},
            "location":{
              "x":152,
              "y":209},
            "size":{
              "width":289,
              "height":83},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11f106c360cc4aa4899cec754bf7ad44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"72px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49,
                  "opacity":1},
                "location":{
                  "x":152,
                  "y":209},
                "size":{
                  "width":289,
                  "height":83},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFE6E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a9eb3434b854503a8288348e912182f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF46E49,
              "opacity":1},
            "location":{
              "x":258,
              "y":302},
            "size":{
              "width":309,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30893aa847cb419cb46c04e4f182c5c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49,
                  "opacity":1},
                "location":{
                  "x":258,
                  "y":302},
                "size":{
                  "width":309,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFE6E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8096aafae5324736b008597bf781efbb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF46E49,
              "opacity":1},
            "location":{
              "x":559,
              "y":607},
            "size":{
              "width":113,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2b43f50ad1748baa29c417b531ad6b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49,
                  "opacity":1},
                "location":{
                  "x":559,
                  "y":607},
                "size":{
                  "width":113,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3685e594d9e048a4812697211a9fd1ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":700},
            "size":{
              "width":624,
              "height":90},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a0372619f8f401da9da01f1a567e65e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":700},
                "size":{
                  "width":624,
                  "height":90},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFE6E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/按钮/u8.png"}},
{
          "id":"43e68f7a25ce45a4a619242c3762dcca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF46E49,
              "opacity":1},
            "location":{
              "x":320,
              "y":724},
            "size":{
              "width":73,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79c42d6ea03f4ab28e063876b88ffbf6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49,
                  "opacity":1},
                "location":{
                  "x":320,
                  "y":724},
                "size":{
                  "width":73,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb20f6b62f534037b177b772a0a8aaf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":220,
              "y":807},
            "size":{
              "width":281,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cec9327359cc4db6a3f795ab68f8d6de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":220,
                  "y":807},
                "size":{
                  "width":281,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5f72a4b6b3747cca7714d4030b550fb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":418,
              "y":992},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76ac3f9d72df42bb99982a36cc593fc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":418,
                  "y":992},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录界面/u50.png"}},
{
          "id":"18a8b6bf465544b68b9dfeb7f2b211da",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":930},
            "size":{
              "width":720,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录界面/u52_line.png"}},
{
          "id":"2c24557ac4f24ec8804a7017fa28da91",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFCFCFC},
            "location":{
              "x":262,
              "y":918},
            "size":{
              "width":197,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95fd71316ac14944a3983a4f0fb52f66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFEAEAEA,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFCFCFC},
                "location":{
                  "x":262,
                  "y":918},
                "size":{
                  "width":197,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录界面/u53.png"}},
{
          "id":"12fb17dfe81a4093bace4d8bf2528b39",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":152,
              "y":991},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c0782f1d7ee4326801301deae2d1d3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":152,
                  "y":991},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录界面/u55.png"}},
{
          "id":"abb1728e99014ea1b10db642c1366bce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":210,
              "y":554},
            "size":{
              "width":171,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffa1324225914f26b5c654228acecb95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":210,
                  "y":554},
                "size":{
                  "width":171,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "35e6af43aa284b25b521cdbc88d23745":{
      "scriptId":"u0"},
    "ba67001c13ad4a449d6209d8f5a998cf":{
      "scriptId":"u1"},
    "bf135e5ee22a4e49b70c0c53fbd6159b":{
      "scriptId":"u2"},
    "d1aa5c37076e4f1ab652663218946542":{
      "scriptId":"u3"},
    "9e1b29d343d640d9b913022fb49d35e6":{
      "scriptId":"u4"},
    "aed8f8f3f4cd447d877f33dfae7cb401":{
      "scriptId":"u5"},
    "b98af60fe3c84de5a8c4a18edf9845cd":{
      "scriptId":"u6"},
    "2227c4debe0e4b45901594a28fd4d49e":{
      "scriptId":"u7"},
    "7bd31098f83748ed9d18100c2cc80700":{
      "scriptId":"u8"},
    "3aad4b310d4e49a0b294a9b4094524b5":{
      "scriptId":"u9"},
    "37d5304df626423fb0ef9602d143fa23":{
      "scriptId":"u10"},
    "42527769f9ec44ee895d0e5a2b31677e":{
      "scriptId":"u11"},
    "264c5e3452204598b2a688078adcf74b":{
      "scriptId":"u12"},
    "49386d7881ed406285667c400c45d333":{
      "scriptId":"u13"},
    "b4d7c6f06a4f403fb56370813e49adcf":{
      "scriptId":"u14"},
    "2c1808c487534e58a51908d6d02b30fb":{
      "scriptId":"u15"},
    "56783ffe90a347d184f8af7a06b2214f":{
      "scriptId":"u16"},
    "b0bedb5f74574c66a55ba6f6bcdd7748":{
      "scriptId":"u17"},
    "d4801bb22e6d4631929c2df2443f09ed":{
      "scriptId":"u18"},
    "f514effade7647babd042b7b2dd1c0ca":{
      "scriptId":"u19"},
    "965ca0ddd0ca420f9bddb491765d7ebb":{
      "scriptId":"u20"},
    "4597da53bfe2476eae9aa445fd28e772":{
      "scriptId":"u21"},
    "47821d7ec5b4491f8410c0b841d9ac39":{
      "scriptId":"u22"},
    "9e49286c0085422ab46387af3e96d710":{
      "scriptId":"u23"},
    "6c64b59e9e664d0db5903e13b77b0250":{
      "scriptId":"u24"},
    "34f7efbb71c74e4b9972073effcd7a6e":{
      "scriptId":"u25"},
    "26e6f7a25644471285c81dd3668a0e91":{
      "scriptId":"u26"},
    "e552d1f784bb4789a1a4eaf50fbc7383":{
      "scriptId":"u27"},
    "50326a4a9f074869ad0781dd5f389f5b":{
      "scriptId":"u28"},
    "eb95e745e7eb40d993cb4012bd88aff7":{
      "scriptId":"u29"},
    "8081d4c2663d48daafbdc98c4b5c2aca":{
      "scriptId":"u30"},
    "924ecee06f6d4015b551e18db3950f19":{
      "scriptId":"u31"},
    "92c22236e477476fa85682ee6fb11821":{
      "scriptId":"u32"},
    "21b181b256884baea799727c656949d6":{
      "scriptId":"u33"},
    "fdf49fbbd7f64cadb2776b69fb666453":{
      "scriptId":"u34"},
    "21a90ed6af164fbdab38f0576a13ffb1":{
      "scriptId":"u35"},
    "f7aadc470d7c4b468a131e43f0de8f49":{
      "scriptId":"u36"},
    "11f106c360cc4aa4899cec754bf7ad44":{
      "scriptId":"u37"},
    "1a9eb3434b854503a8288348e912182f":{
      "scriptId":"u38"},
    "30893aa847cb419cb46c04e4f182c5c6":{
      "scriptId":"u39"},
    "8096aafae5324736b008597bf781efbb":{
      "scriptId":"u40"},
    "c2b43f50ad1748baa29c417b531ad6b2":{
      "scriptId":"u41"},
    "3685e594d9e048a4812697211a9fd1ef":{
      "scriptId":"u42"},
    "3a0372619f8f401da9da01f1a567e65e":{
      "scriptId":"u43"},
    "43e68f7a25ce45a4a619242c3762dcca":{
      "scriptId":"u44"},
    "79c42d6ea03f4ab28e063876b88ffbf6":{
      "scriptId":"u45"},
    "eb20f6b62f534037b177b772a0a8aaf2":{
      "scriptId":"u46"},
    "cec9327359cc4db6a3f795ab68f8d6de":{
      "scriptId":"u47"},
    "d5f72a4b6b3747cca7714d4030b550fb":{
      "scriptId":"u48"},
    "76ac3f9d72df42bb99982a36cc593fc4":{
      "scriptId":"u49"},
    "18a8b6bf465544b68b9dfeb7f2b211da":{
      "scriptId":"u50"},
    "2c24557ac4f24ec8804a7017fa28da91":{
      "scriptId":"u51"},
    "95fd71316ac14944a3983a4f0fb52f66":{
      "scriptId":"u52"},
    "12fb17dfe81a4093bace4d8bf2528b39":{
      "scriptId":"u53"},
    "9c0782f1d7ee4326801301deae2d1d3b":{
      "scriptId":"u54"},
    "abb1728e99014ea1b10db642c1366bce":{
      "scriptId":"u55"},
    "ffa1324225914f26b5c654228acecb95":{
      "scriptId":"u56"}}});