$axure.loadCurrentPage({
  "url":"招聘列表条目.html",
  "generationDate":new Date(1414911757180.43),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4f3f862b849041229d969ea9dec5fadd",
    "type":"Axure:Page",
    "name":"招聘列表条目",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d10491c27fe9491f9d417bd9ea1a5473",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":720,
              "height":240}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"738feaa265b1483cbd5ba9537f15228c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":720,
                  "height":240}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘列表条目/u0.png"}},
{
          "id":"458a6c75c49d4b82be0df8ceffab27a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":200,
              "height":200},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1f54bf0ad8540dba7f0faf4b9f83a62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":200,
                  "height":200},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘列表条目/u2.png"}},
{
          "id":"d56959dbf9074ef0a4502c230fa98535",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":260,
              "y":20},
            "size":{
              "width":113,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"768da870489740b4adfb22f62c8bf7eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":260,
                  "y":20},
                "size":{
                  "width":113,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6c5e4a5ff7d42a0ae01b5e3bf2e1073",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Light', '微软雅黑'",
            "fontSize":"24px",
            "fontWeight":"290",
            "location":{
              "x":260,
              "y":80},
            "size":{
              "width":310,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9416d8316d54a43b1ed8fe944aa20bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Light', '微软雅黑'",
                "fontSize":"24px",
                "fontWeight":"290",
                "location":{
                  "x":260,
                  "y":80},
                "size":{
                  "width":310,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f2cce91802f42dbab129e2b7981b148",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":260,
              "y":187},
            "size":{
              "width":147,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2207a435c6f4ef399f3b39079a20ea2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":260,
                  "y":187},
                "size":{
                  "width":147,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81bc9c2f03fc42dd82d7305d4b49d3ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":603,
              "y":20},
            "size":{
              "width":97,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec496861a652448fb11d471e7fd7b193",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":603,
                  "y":20},
                "size":{
                  "width":97,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b18335fb846d4b7e95e1dc0fe571d4f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":650,
              "y":170},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddf472c5d5b54264b8b7067206557f91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":650,
                  "y":170},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘列表条目/u12.png"}},
{
          "id":"776264d7dbc8440d86e18004fbbc4303",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":646,
              "y":63},
            "size":{
              "width":54,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe14a3f542b7435cba3cd10accb017b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":646,
                  "y":63},
                "size":{
                  "width":54,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c899559cf4404bd1acc3a9fd42ec9579",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":230},
            "size":{
              "width":460,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/招聘列表条目/u16_line.png"}},
{
          "id":"189b3ab9bfdf4aba8ad04838819d1c28",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":380},
            "size":{
              "width":720,
              "height":186},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"237458f2f6774ab79ab6321e3d980a1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":380},
                "size":{
                  "width":720,
                  "height":186},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘列表条目/u17.png"}},
{
          "id":"65f1202ccdd64dd09c44c24d69ad59a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":20,
              "y":400},
            "size":{
              "width":150,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"684ed0fafcd542be87dbc6e33da226bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":20,
                  "y":400},
                "size":{
                  "width":150,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘列表条目/u19.png"}},
{
          "id":"289ff49e8d1e477e98f32c400e81a2ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":200,
              "y":400},
            "size":{
              "width":113,
              "height":33},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48da54138fc146d49b92ed1938c33538",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":200,
                  "y":400},
                "size":{
                  "width":113,
                  "height":33},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"73765f69a24b45ddaad9c4d1f36d0794",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Light', '微软雅黑'",
            "fontSize":"24px",
            "fontWeight":"290",
            "location":{
              "x":200,
              "y":443},
            "size":{
              "width":380,
              "height":62},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"665870dddd194d8e965c4250c0fbc13c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Light', '微软雅黑'",
                "fontSize":"24px",
                "fontWeight":"290",
                "location":{
                  "x":200,
                  "y":443},
                "size":{
                  "width":380,
                  "height":62},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56493ed9c997473a8c2d3a19c242f06b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":200,
              "y":515},
            "size":{
              "width":103,
              "height":24},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c34e2c8698ab40b29ca3310348209e52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":515},
                "size":{
                  "width":103,
                  "height":24},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"70122bb13f3c459abd002fea1d6805bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":603,
              "y":400},
            "size":{
              "width":97,
              "height":33},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a7a4811fdde4ed180ad2a3972ba0914",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":603,
                  "y":400},
                "size":{
                  "width":97,
                  "height":33},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1b5bba628c04f39aae8f87a7f180c44",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":654,
              "y":489},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b044d6ced35e4156aff9e0c8993c0927",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":654,
                  "y":489},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘列表条目/u29.png"}},
{
          "id":"fa6ae21965b844cd883feae3b9e23b17",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":646,
              "y":439},
            "size":{
              "width":54,
              "height":24},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"521817115e8f48048e729620bb38d418",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":646,
                  "y":439},
                "size":{
                  "width":54,
                  "height":24},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53f9fe6dc2734be7a3a502639e0053bf",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":559},
            "size":{
              "width":520,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/招聘列表条目/u33_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "d10491c27fe9491f9d417bd9ea1a5473":{
      "scriptId":"u0"},
    "738feaa265b1483cbd5ba9537f15228c":{
      "scriptId":"u1"},
    "458a6c75c49d4b82be0df8ceffab27a4":{
      "scriptId":"u2"},
    "c1f54bf0ad8540dba7f0faf4b9f83a62":{
      "scriptId":"u3"},
    "d56959dbf9074ef0a4502c230fa98535":{
      "scriptId":"u4"},
    "768da870489740b4adfb22f62c8bf7eb":{
      "scriptId":"u5"},
    "b6c5e4a5ff7d42a0ae01b5e3bf2e1073":{
      "scriptId":"u6"},
    "d9416d8316d54a43b1ed8fe944aa20bb":{
      "scriptId":"u7"},
    "7f2cce91802f42dbab129e2b7981b148":{
      "scriptId":"u8"},
    "b2207a435c6f4ef399f3b39079a20ea2":{
      "scriptId":"u9"},
    "81bc9c2f03fc42dd82d7305d4b49d3ac":{
      "scriptId":"u10"},
    "ec496861a652448fb11d471e7fd7b193":{
      "scriptId":"u11"},
    "b18335fb846d4b7e95e1dc0fe571d4f7":{
      "scriptId":"u12"},
    "ddf472c5d5b54264b8b7067206557f91":{
      "scriptId":"u13"},
    "776264d7dbc8440d86e18004fbbc4303":{
      "scriptId":"u14"},
    "fe14a3f542b7435cba3cd10accb017b7":{
      "scriptId":"u15"},
    "c899559cf4404bd1acc3a9fd42ec9579":{
      "scriptId":"u16"},
    "189b3ab9bfdf4aba8ad04838819d1c28":{
      "scriptId":"u17"},
    "237458f2f6774ab79ab6321e3d980a1d":{
      "scriptId":"u18"},
    "65f1202ccdd64dd09c44c24d69ad59a1":{
      "scriptId":"u19"},
    "684ed0fafcd542be87dbc6e33da226bb":{
      "scriptId":"u20"},
    "289ff49e8d1e477e98f32c400e81a2ff":{
      "scriptId":"u21"},
    "48da54138fc146d49b92ed1938c33538":{
      "scriptId":"u22"},
    "73765f69a24b45ddaad9c4d1f36d0794":{
      "scriptId":"u23"},
    "665870dddd194d8e965c4250c0fbc13c":{
      "scriptId":"u24"},
    "56493ed9c997473a8c2d3a19c242f06b":{
      "scriptId":"u25"},
    "c34e2c8698ab40b29ca3310348209e52":{
      "scriptId":"u26"},
    "70122bb13f3c459abd002fea1d6805bf":{
      "scriptId":"u27"},
    "5a7a4811fdde4ed180ad2a3972ba0914":{
      "scriptId":"u28"},
    "a1b5bba628c04f39aae8f87a7f180c44":{
      "scriptId":"u29"},
    "b044d6ced35e4156aff9e0c8993c0927":{
      "scriptId":"u30"},
    "fa6ae21965b844cd883feae3b9e23b17":{
      "scriptId":"u31"},
    "521817115e8f48048e729620bb38d418":{
      "scriptId":"u32"},
    "53f9fe6dc2734be7a3a502639e0053bf":{
      "scriptId":"u33"}}});