$axure.loadCurrentPage({
  "url":"文本输入.html",
  "generationDate":new Date(1414911756943.29),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c5286048d2f649368d5769871c67c565",
    "type":"Axure:Page",
    "name":"文本输入",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d550e9c0b6cf4673a55b75fd9d9c02bc",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":66,
              "y":100},
            "size":{
              "width":624,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u0_line.png"}},
{
          "id":"180a37ac6d0a4f99ae4378acfc2be87a",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":62,
              "y":98},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u1_line.png"}},
{
          "id":"c572623ddede43c6b732b5a1a7162f65",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":684,
              "y":98},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u1_line.png"}},
{
          "id":"b3bd124fc6d8460185ecc19cff166fcd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":66,
              "y":214},
            "size":{
              "width":624,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u3_line.png"}},
{
          "id":"7c7d3416a4574739b9adb50831eb5333",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":62,
              "y":212},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u4_line.png"}},
{
          "id":"bf22ac79a2f546afb78ee02ef0eaa5d1",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":684,
              "y":212},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u4_line.png"}},
{
          "id":"23f87a3df4a74b008a2dbca2fa532f34",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":66,
              "y":157},
            "size":{
              "width":624,
              "height":10},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u6_line.png"}},
{
          "id":"5174f378d25147eaa4cf4a822de5cab2",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":62,
              "y":155},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u7_line.png"}},
{
          "id":"2efc4043e14a499da0bc3305bfb4a289",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":684,
              "y":155},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u7_line.png"}},
{
          "id":"3bc83318bcf64c89a1d809e6aa6ade5c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":66,
              "y":487},
            "size":{
              "width":624,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u0_line.png"}},
{
          "id":"174df091e5a3412ea8a5cf4962518b93",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":62,
              "y":485},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u1_line.png"}},
{
          "id":"353ee93b6a7a4672aef44f7e4be18494",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":684,
              "y":485},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u1_line.png"}},
{
          "id":"d4d8416a3b504741ae5a3e6ce1675313",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":82,
              "y":451},
            "size":{
              "width":57,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"040d525c684443819fac0a9c5c2ea866",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":82,
                  "y":451},
                "size":{
                  "width":57,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b91ad8d48f7431f82e9c5201af50366",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA,
              "opacity":1},
            "location":{
              "x":154,
              "y":451},
            "size":{
              "width":169,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8694815e595640098a7f216911141cd6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFEAEAEA,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":451},
                "size":{
                  "width":169,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"801b604ceece4d428d5c0b02d7dea006",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":66,
              "y":578},
            "size":{
              "width":624,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u3_line.png"}},
{
          "id":"b89864ec2d3a447695ad19a9072590f0",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":62,
              "y":576},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u4_line.png"}},
{
          "id":"11f18dba0e1243188101fe43841240ac",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":684,
              "y":576},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u4_line.png"}},
{
          "id":"93e39dfc728b4536bcca475fde73173b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":82,
              "y":542},
            "size":{
              "width":57,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f95b2a98a3d947cbae211b8e2f66a96b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":82,
                  "y":542},
                "size":{
                  "width":57,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c84aece908ad4d0d86a2e194db678f4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA,
              "opacity":1},
            "location":{
              "x":154,
              "y":542},
            "size":{
              "width":169,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"818af7c4fd2d46c7bd50d1d796b63c29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFEAEAEA,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":542},
                "size":{
                  "width":169,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"41c7b9753aae4dc5b6443bb30a6a7a23",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":66,
              "y":669},
            "size":{
              "width":624,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u0_line.png"}},
{
          "id":"6d7bc772ea004781aee5e001f642c47b",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":62,
              "y":667},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u1_line.png"}},
{
          "id":"c346af8c968a4c5cb8821620608c57de",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":684,
              "y":667},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u1_line.png"}},
{
          "id":"953e5014dae944ceb64825339351ad5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":134,
              "y":633},
            "size":{
              "width":57,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67fb6667248b406bbbc6aad5a5f6c169",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":134,
                  "y":633},
                "size":{
                  "width":57,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a59ece42fe24e79a877cbee828d6a85",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA,
              "opacity":1},
            "location":{
              "x":206,
              "y":633},
            "size":{
              "width":169,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c48a0616d33945c5b7aa6a32b7735e8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFEAEAEA,
                  "opacity":1},
                "location":{
                  "x":206,
                  "y":633},
                "size":{
                  "width":169,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6f00144b1fc48db9a1317a5ae39e420",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":85,
              "y":634},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33a4bb96648e49098bf136bf42f5dd29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":85,
                  "y":634},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文本输入/u30.png"}},
{
          "id":"aa38068f56de41de860ba1d978dee9e8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":66,
              "y":760},
            "size":{
              "width":624,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u3_line.png"}},
{
          "id":"64926e02f87f4d0b8628614314e22880",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":62,
              "y":758},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u4_line.png"}},
{
          "id":"fa963abf9b6d48549445b9abc2787cbd",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":684,
              "y":758},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u4_line.png"}},
{
          "id":"856a2d3aaa5947ccb21ef5e51438538e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":134,
              "y":724},
            "size":{
              "width":57,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"104867afeb0e4efe99295775d49f8f10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":134,
                  "y":724},
                "size":{
                  "width":57,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEAEAEA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d8d4600da3a4a6880a79147dca34284",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA,
              "opacity":1},
            "location":{
              "x":206,
              "y":724},
            "size":{
              "width":169,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d728ae3dc5d4819b20a825a060798b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFEAEAEA,
                  "opacity":1},
                "location":{
                  "x":206,
                  "y":724},
                "size":{
                  "width":169,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEAEAEA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"446f4b8b895445cf964e18484c2295c4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":85,
              "y":725},
            "size":{
              "width":32,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0c2ed2d1e65453ba7f0324db5160ab9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":85,
                  "y":725},
                "size":{
                  "width":32,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEAEAEA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文本输入/u30.png"}},
{
          "id":"ea0762a41e1e4168942a8067053b8dee",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":66,
              "y":305},
            "size":{
              "width":624,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u0_line.png"}},
{
          "id":"c947a9102bec47be94914fbdaa23d375",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":62,
              "y":303},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u1_line.png"}},
{
          "id":"026e1eb6b1a84abfb467167ab56102a3",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":684,
              "y":303},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u1_line.png"}},
{
          "id":"dae61ebdf4c24fa48d5befa0af47d32c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA,
              "opacity":1},
            "location":{
              "x":82,
              "y":269},
            "size":{
              "width":169,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5731eb538ea349dea5e753149c126378",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFEAEAEA,
                  "opacity":1},
                "location":{
                  "x":82,
                  "y":269},
                "size":{
                  "width":169,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a3a0384a3794d8080d69dd6b18a30ea",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":66,
              "y":396},
            "size":{
              "width":624,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u3_line.png"}},
{
          "id":"a1566f95ff4c4bbe80012efdf5c1de71",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":62,
              "y":394},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u4_line.png"}},
{
          "id":"68d58fb0395e44759d901d96549a641e",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":684,
              "y":394},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u4_line.png"}},
{
          "id":"eb3debebb27e465e91dd7e990498bc70",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA,
              "opacity":1},
            "location":{
              "x":82,
              "y":360},
            "size":{
              "width":169,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a49fddfdde6f43fcba7ac908e82ce71b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFEAEAEA,
                  "opacity":1},
                "location":{
                  "x":82,
                  "y":360},
                "size":{
                  "width":169,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEAEAEA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "d550e9c0b6cf4673a55b75fd9d9c02bc":{
      "scriptId":"u0"},
    "180a37ac6d0a4f99ae4378acfc2be87a":{
      "scriptId":"u1"},
    "c572623ddede43c6b732b5a1a7162f65":{
      "scriptId":"u2"},
    "b3bd124fc6d8460185ecc19cff166fcd":{
      "scriptId":"u3"},
    "7c7d3416a4574739b9adb50831eb5333":{
      "scriptId":"u4"},
    "bf22ac79a2f546afb78ee02ef0eaa5d1":{
      "scriptId":"u5"},
    "23f87a3df4a74b008a2dbca2fa532f34":{
      "scriptId":"u6"},
    "5174f378d25147eaa4cf4a822de5cab2":{
      "scriptId":"u7"},
    "2efc4043e14a499da0bc3305bfb4a289":{
      "scriptId":"u8"},
    "3bc83318bcf64c89a1d809e6aa6ade5c":{
      "scriptId":"u9"},
    "174df091e5a3412ea8a5cf4962518b93":{
      "scriptId":"u10"},
    "353ee93b6a7a4672aef44f7e4be18494":{
      "scriptId":"u11"},
    "d4d8416a3b504741ae5a3e6ce1675313":{
      "scriptId":"u12"},
    "040d525c684443819fac0a9c5c2ea866":{
      "scriptId":"u13"},
    "0b91ad8d48f7431f82e9c5201af50366":{
      "scriptId":"u14"},
    "8694815e595640098a7f216911141cd6":{
      "scriptId":"u15"},
    "801b604ceece4d428d5c0b02d7dea006":{
      "scriptId":"u16"},
    "b89864ec2d3a447695ad19a9072590f0":{
      "scriptId":"u17"},
    "11f18dba0e1243188101fe43841240ac":{
      "scriptId":"u18"},
    "93e39dfc728b4536bcca475fde73173b":{
      "scriptId":"u19"},
    "f95b2a98a3d947cbae211b8e2f66a96b":{
      "scriptId":"u20"},
    "c84aece908ad4d0d86a2e194db678f4e":{
      "scriptId":"u21"},
    "818af7c4fd2d46c7bd50d1d796b63c29":{
      "scriptId":"u22"},
    "41c7b9753aae4dc5b6443bb30a6a7a23":{
      "scriptId":"u23"},
    "6d7bc772ea004781aee5e001f642c47b":{
      "scriptId":"u24"},
    "c346af8c968a4c5cb8821620608c57de":{
      "scriptId":"u25"},
    "953e5014dae944ceb64825339351ad5c":{
      "scriptId":"u26"},
    "67fb6667248b406bbbc6aad5a5f6c169":{
      "scriptId":"u27"},
    "2a59ece42fe24e79a877cbee828d6a85":{
      "scriptId":"u28"},
    "c48a0616d33945c5b7aa6a32b7735e8a":{
      "scriptId":"u29"},
    "c6f00144b1fc48db9a1317a5ae39e420":{
      "scriptId":"u30"},
    "33a4bb96648e49098bf136bf42f5dd29":{
      "scriptId":"u31"},
    "aa38068f56de41de860ba1d978dee9e8":{
      "scriptId":"u32"},
    "64926e02f87f4d0b8628614314e22880":{
      "scriptId":"u33"},
    "fa963abf9b6d48549445b9abc2787cbd":{
      "scriptId":"u34"},
    "856a2d3aaa5947ccb21ef5e51438538e":{
      "scriptId":"u35"},
    "104867afeb0e4efe99295775d49f8f10":{
      "scriptId":"u36"},
    "8d8d4600da3a4a6880a79147dca34284":{
      "scriptId":"u37"},
    "8d728ae3dc5d4819b20a825a060798b1":{
      "scriptId":"u38"},
    "446f4b8b895445cf964e18484c2295c4":{
      "scriptId":"u39"},
    "c0c2ed2d1e65453ba7f0324db5160ab9":{
      "scriptId":"u40"},
    "ea0762a41e1e4168942a8067053b8dee":{
      "scriptId":"u41"},
    "c947a9102bec47be94914fbdaa23d375":{
      "scriptId":"u42"},
    "026e1eb6b1a84abfb467167ab56102a3":{
      "scriptId":"u43"},
    "dae61ebdf4c24fa48d5befa0af47d32c":{
      "scriptId":"u44"},
    "5731eb538ea349dea5e753149c126378":{
      "scriptId":"u45"},
    "8a3a0384a3794d8080d69dd6b18a30ea":{
      "scriptId":"u46"},
    "a1566f95ff4c4bbe80012efdf5c1de71":{
      "scriptId":"u47"},
    "68d58fb0395e44759d901d96549a641e":{
      "scriptId":"u48"},
    "eb3debebb27e465e91dd7e990498bc70":{
      "scriptId":"u49"},
    "a49fddfdde6f43fcba7ac908e82ce71b":{
      "scriptId":"u50"}}});