$axure.loadCurrentPage({
  "url":"单选框和复选框.html",
  "generationDate":new Date(1414911757113.4),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3849c645f1a6466c9e050b6cdaf10bfa",
    "type":"Axure:Page",
    "name":"单选框和复选框",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4b1b037fdb4349bfb78f995a04635bc5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":84,
              "y":184},
            "size":{
              "width":36,
              "height":36},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f3251f1d8254dd79c774f4287f3cfc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":84,
                  "y":184},
                "size":{
                  "width":36,
                  "height":36},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFE6E49},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/单选框和复选框/u0.png"}},
{
          "id":"5e68cfb998c741a4b7c816e7528f7998",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":86,
              "y":186},
            "size":{
              "width":32,
              "height":32},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"164efe8dc55a4a26bec9f93dbddf7e5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":86,
                  "y":186},
                "size":{
                  "width":32,
                  "height":32},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFE6E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/单选框和复选框/u2.png"}},
{
          "id":"abc737c2bad44a38ac1bb6ac9cbaa7f4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":88,
              "y":201},
            "size":{
              "width":12,
              "height":10},
            "rotation":"45",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/单选框和复选框/u4_line.png"}},
{
          "id":"21f2f88d651c4557993c8c32d838f0f8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":93,
              "y":197},
            "size":{
              "width":25,
              "height":10},
            "rotation":"315",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/单选框和复选框/u5_line.png"}},
{
          "id":"b8478b0a03b947129ad1e7f519f855ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xEAEAEA},
            "location":{
              "x":160,
              "y":184},
            "size":{
              "width":36,
              "height":36},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2997c63c6e3e4883aa5694d878e50d96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xEAEAEA},
                "location":{
                  "x":160,
                  "y":184},
                "size":{
                  "width":36,
                  "height":36},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEAEAEA},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/单选框和复选框/u6.png"}},
{
          "id":"a12d335c5ec841818db2c8ff444e7b80",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEAEAEA},
            "location":{
              "x":162,
              "y":186},
            "size":{
              "width":32,
              "height":32},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af1f7d4c110d48e8bd043b4a6bfe827d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEAEAEA},
                "location":{
                  "x":162,
                  "y":186},
                "size":{
                  "width":32,
                  "height":32},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEAEAEA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/单选框和复选框/u8.png"}},
{
          "id":"0e70d294a0384afb90f149be46e01030",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":74,
              "y":80},
            "size":{
              "width":40,
              "height":40},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bec2219cad774e4cade2e7e3b449a23d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":74,
                  "y":80},
                "size":{
                  "width":40,
                  "height":40},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/单选框和复选框/u10.png"}},
{
          "id":"dd3d41fd18144982a82200aa726c686f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":84,
              "y":90},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5d387ea99a14e2597909c734d90d055",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":84,
                  "y":90},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/单选框和复选框/u12.png"}},
{
          "id":"650323e39b704a0898581e8443416433",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEAEAEA},
            "location":{
              "x":160,
              "y":80},
            "size":{
              "width":40,
              "height":40},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2c4be5f725843129ed284b3e9450ea0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEAEAEA},
                "location":{
                  "x":160,
                  "y":80},
                "size":{
                  "width":40,
                  "height":40},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEAEAEA},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/单选框和复选框/u14.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "4b1b037fdb4349bfb78f995a04635bc5":{
      "scriptId":"u0"},
    "5f3251f1d8254dd79c774f4287f3cfc6":{
      "scriptId":"u1"},
    "5e68cfb998c741a4b7c816e7528f7998":{
      "scriptId":"u2"},
    "164efe8dc55a4a26bec9f93dbddf7e5f":{
      "scriptId":"u3"},
    "abc737c2bad44a38ac1bb6ac9cbaa7f4":{
      "scriptId":"u4"},
    "21f2f88d651c4557993c8c32d838f0f8":{
      "scriptId":"u5"},
    "b8478b0a03b947129ad1e7f519f855ce":{
      "scriptId":"u6"},
    "2997c63c6e3e4883aa5694d878e50d96":{
      "scriptId":"u7"},
    "a12d335c5ec841818db2c8ff444e7b80":{
      "scriptId":"u8"},
    "af1f7d4c110d48e8bd043b4a6bfe827d":{
      "scriptId":"u9"},
    "0e70d294a0384afb90f149be46e01030":{
      "scriptId":"u10"},
    "bec2219cad774e4cade2e7e3b449a23d":{
      "scriptId":"u11"},
    "dd3d41fd18144982a82200aa726c686f":{
      "scriptId":"u12"},
    "a5d387ea99a14e2597909c734d90d055":{
      "scriptId":"u13"},
    "650323e39b704a0898581e8443416433":{
      "scriptId":"u14"},
    "a2c4be5f725843129ed284b3e9450ea0":{
      "scriptId":"u15"}}});