$axure.loadCurrentPage({
  "url":"快速注册_-_1.html",
  "generationDate":new Date(1414911758595.4),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2a5a964b30c742629aeb39e42e7a93fc",
    "type":"Axure:Page",
    "name":"快速注册 - 1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"895444b260d04e0d9b9115c922e59da3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFCFCFC},
            "size":{
              "width":720,
              "height":1280},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFCFCFC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"937b74e02e484a2e81e2f63633a5e12d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFCFCFC},
                "size":{
                  "width":720,
                  "height":1280},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFCFCFC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u0.png"}},
{
          "id":"fc928b00e61440aeba14a196f6016bdc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":0,
              "y":1182},
            "size":{
              "width":720,
              "height":98},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78975885eb6c4e52be4f02cb2614ae49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":0,
                  "y":1182},
                "size":{
                  "width":720,
                  "height":98},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u2.png"}},
{
          "id":"daa12727f6c546efae35b9924b6647a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":137,
              "y":1206},
            "size":{
              "width":42,
              "height":50},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA2A2A2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3a9e0a5d37f42368f5d5e14d86ab8ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":137,
                  "y":1206},
                "size":{
                  "width":42,
                  "height":50},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA2A2A2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u4.png"}},
{
          "id":"5f929680eeee4b4aaa5f25634e65c251",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":335,
              "y":1206},
            "size":{
              "width":50,
              "height":50},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA2A2A2},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0345042a89814733aa2435c81e1773e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":335,
                  "y":1206},
                "size":{
                  "width":50,
                  "height":50},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA2A2A2},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u6.png"}},
{
          "id":"d6efc948cd774623b96e950f594965ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":541,
              "y":1209},
            "size":{
              "width":44,
              "height":44},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA2A2A2},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8810217474f4629bf21e4aa65771a40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":541,
                  "y":1209},
                "size":{
                  "width":44,
                  "height":44},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA2A2A2},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u8.png"}},
{
          "id":"051263ae01de462b940a5ae5251a012f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000}]},
            "size":{
              "width":720,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFB3B3B3}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0b732c7c12846d88bee121406b7403c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000}]},
                "size":{
                  "width":720,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFB3B3B3}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u10.png"}},
{
          "id":"094d3856d57947c3934292ed9a46b57b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Roboto Thin', 'Roboto'",
            "fontWeight":"250",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF8F8FA,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000}]},
            "location":{
              "x":642,
              "y":10},
            "size":{
              "width":51,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50fc0f5ce87341e38faddabe65530d75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Thin', 'Roboto'",
                "fontWeight":"250",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF8F8FA,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000}]},
                "location":{
                  "x":642,
                  "y":10},
                "size":{
                  "width":51,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u12.png"}},
{
          "id":"b4d3a255e04f4d1aa30e61fd4a357519",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000}]},
            "location":{
              "x":604,
              "y":23},
            "size":{
              "width":18,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b712a10eec143679184dbc4d8fd79be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000}]},
                "location":{
                  "x":604,
                  "y":23},
                "size":{
                  "width":18,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/忘记密码/u14.png"}},
{
          "id":"06b7434fe29b44c2ab3bb25125c25771",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000}]},
            "location":{
              "x":604,
              "y":11},
            "size":{
              "width":18,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3c6180e2cbe4cee9677523f40db4242",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000}]},
                "location":{
                  "x":604,
                  "y":11},
                "size":{
                  "width":18,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/忘记密码/u14.png"}},
{
          "id":"7913f53702544901b915f4f35d5a8792",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000}]},
            "location":{
              "x":608,
              "y":9},
            "size":{
              "width":8,
              "height":2},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC6C6C6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1f0d884d6a3441181c05a046b550632",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000}]},
                "location":{
                  "x":608,
                  "y":9},
                "size":{
                  "width":8,
                  "height":2},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC6C6C6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u18.png"}},
{
          "id":"21c3046c70ee4b98835e51d42aa49a79",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":0,
              "y":48},
            "size":{
              "width":720,
              "height":100},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f86ab87c285f42df96429869f1198d37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":0,
                  "y":48},
                "size":{
                  "width":720,
                  "height":100},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFE6E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航栏/u0.png"}},
{
          "id":"808a4b2467d04c998dd5db00854c1da1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":100,
              "y":77},
            "size":{
              "width":145,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd3101a6d4d04986a74a4e7a65d3444f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":100,
                  "y":77},
                "size":{
                  "width":145,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02613c98036144c982bf58c32cc8a266",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":75},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"045ca5e141d742d68f3722fa5997ed46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":75},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/忘记密码/u24.png"}},
{
          "id":"359d42f55de241f4b44d43c2185b26c9",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":464,
              "y":237},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u1_line.png"}},
{
          "id":"c9b272ed2dfb42e9bb5b1ce48bc042fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0BAA9E,
              "opacity":1},
            "location":{
              "x":539,
              "y":203},
            "size":{
              "width":61,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"693c3f62eabf4b93851574e17863c6d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0BAA9E,
                  "opacity":1},
                "location":{
                  "x":539,
                  "y":203},
                "size":{
                  "width":61,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35bca7801aaa45e3bea9279cb9b1fd95",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":239},
            "size":{
              "width":624,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u0_line.png"}},
{
          "id":"595d0d8401ea416e9b80b5badaf3a339",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":237},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u1_line.png"}},
{
          "id":"7b7d7475b2684be797e8a9bb1429dfb9",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":666,
              "y":237},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u1_line.png"}},
{
          "id":"98795378475947efa3a204eb5c9bfb5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":64,
              "y":203},
            "size":{
              "width":81,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18e1a27c02c846c590a028ba4cfd6451",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":64,
                  "y":203},
                "size":{
                  "width":81,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e95f6a5197b647228ef69e01cb6920e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":171,
              "y":203},
            "size":{
              "width":191,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59aafdd7692142af831d4905369f3431",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":171,
                  "y":203},
                "size":{
                  "width":191,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e5db5c0e1d54d46b6fbbc522afb2458",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":330},
            "size":{
              "width":624,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u3_line.png"}},
{
          "id":"d7f088ed050f49f5bcabd5fcc985017e",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":328},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u4_line.png"}},
{
          "id":"ac2cf7d2bd5c4a3a868038cdada2dbbe",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":666,
              "y":328},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u4_line.png"}},
{
          "id":"e68f42f9ad4442919514f4cb8a0412a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":64,
              "y":294},
            "size":{
              "width":85,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e48b6df3eac24db6ae9311e3abde5222",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":64,
                  "y":294},
                "size":{
                  "width":85,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f3b564b17f07480683839a1025e62ea8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA,
              "opacity":1},
            "location":{
              "x":171,
              "y":294},
            "size":{
              "width":309,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23478d69837244e9b4e765f4bb702898",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFEAEAEA,
                  "opacity":1},
                "location":{
                  "x":171,
                  "y":294},
                "size":{
                  "width":309,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"62bfcf0ab37d472c9503fdb9439546b8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":52,
              "y":421},
            "size":{
              "width":624,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u3_line.png"}},
{
          "id":"0bb420b2564b41f0bb1a1a392def14ce",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":419},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u4_line.png"}},
{
          "id":"054d15be71d5433baa85f0b50f0cd54e",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":419},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u4_line.png"}},
{
          "id":"bdaae79761424fbaa2dd8255f20c9aa8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":68,
              "y":385},
            "size":{
              "width":73,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe2cbbc5b8494c5f8b939965049f1342",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":68,
                  "y":385},
                "size":{
                  "width":73,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"51791c2558864742a180a0832784a2b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA,
              "opacity":1},
            "location":{
              "x":175,
              "y":385},
            "size":{
              "width":310,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0dbc9b109b014e14930fb1844c1e541c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFEAEAEA,
                  "opacity":1},
                "location":{
                  "x":175,
                  "y":385},
                "size":{
                  "width":310,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b5ca6a4c5ad47438e7a64be2598d0cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":516},
            "size":{
              "width":624,
              "height":90},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ea1aa4e807746028db7ce28a82264de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":516},
                "size":{
                  "width":624,
                  "height":90},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFE6E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/按钮/u8.png"}},
{
          "id":"a5468a2e0a8b40238c22775ae524ca89",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF46E49,
              "opacity":1},
            "location":{
              "x":324,
              "y":540},
            "size":{
              "width":73,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea95bb1fbe464749ba9e78a5d5c36b8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49,
                  "opacity":1},
                "location":{
                  "x":324,
                  "y":540},
                "size":{
                  "width":73,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c142b36011b47378a2f51852bbf301b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0BAA9E,
              "opacity":1},
            "location":{
              "x":192,
              "y":1090},
            "size":{
              "width":337,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f365a39f6215430ea8f75eb0b6c34873",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0BAA9E,
                  "opacity":1},
                "location":{
                  "x":192,
                  "y":1090},
                "size":{
                  "width":337,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "895444b260d04e0d9b9115c922e59da3":{
      "scriptId":"u0"},
    "937b74e02e484a2e81e2f63633a5e12d":{
      "scriptId":"u1"},
    "fc928b00e61440aeba14a196f6016bdc":{
      "scriptId":"u2"},
    "78975885eb6c4e52be4f02cb2614ae49":{
      "scriptId":"u3"},
    "daa12727f6c546efae35b9924b6647a6":{
      "scriptId":"u4"},
    "c3a9e0a5d37f42368f5d5e14d86ab8ba":{
      "scriptId":"u5"},
    "5f929680eeee4b4aaa5f25634e65c251":{
      "scriptId":"u6"},
    "0345042a89814733aa2435c81e1773e4":{
      "scriptId":"u7"},
    "d6efc948cd774623b96e950f594965ac":{
      "scriptId":"u8"},
    "e8810217474f4629bf21e4aa65771a40":{
      "scriptId":"u9"},
    "051263ae01de462b940a5ae5251a012f":{
      "scriptId":"u10"},
    "e0b732c7c12846d88bee121406b7403c":{
      "scriptId":"u11"},
    "094d3856d57947c3934292ed9a46b57b":{
      "scriptId":"u12"},
    "50fc0f5ce87341e38faddabe65530d75":{
      "scriptId":"u13"},
    "b4d3a255e04f4d1aa30e61fd4a357519":{
      "scriptId":"u14"},
    "3b712a10eec143679184dbc4d8fd79be":{
      "scriptId":"u15"},
    "06b7434fe29b44c2ab3bb25125c25771":{
      "scriptId":"u16"},
    "f3c6180e2cbe4cee9677523f40db4242":{
      "scriptId":"u17"},
    "7913f53702544901b915f4f35d5a8792":{
      "scriptId":"u18"},
    "e1f0d884d6a3441181c05a046b550632":{
      "scriptId":"u19"},
    "21c3046c70ee4b98835e51d42aa49a79":{
      "scriptId":"u20"},
    "f86ab87c285f42df96429869f1198d37":{
      "scriptId":"u21"},
    "808a4b2467d04c998dd5db00854c1da1":{
      "scriptId":"u22"},
    "dd3101a6d4d04986a74a4e7a65d3444f":{
      "scriptId":"u23"},
    "02613c98036144c982bf58c32cc8a266":{
      "scriptId":"u24"},
    "045ca5e141d742d68f3722fa5997ed46":{
      "scriptId":"u25"},
    "359d42f55de241f4b44d43c2185b26c9":{
      "scriptId":"u26"},
    "c9b272ed2dfb42e9bb5b1ce48bc042fa":{
      "scriptId":"u27"},
    "693c3f62eabf4b93851574e17863c6d9":{
      "scriptId":"u28"},
    "35bca7801aaa45e3bea9279cb9b1fd95":{
      "scriptId":"u29"},
    "595d0d8401ea416e9b80b5badaf3a339":{
      "scriptId":"u30"},
    "7b7d7475b2684be797e8a9bb1429dfb9":{
      "scriptId":"u31"},
    "98795378475947efa3a204eb5c9bfb5f":{
      "scriptId":"u32"},
    "18e1a27c02c846c590a028ba4cfd6451":{
      "scriptId":"u33"},
    "e95f6a5197b647228ef69e01cb6920e1":{
      "scriptId":"u34"},
    "59aafdd7692142af831d4905369f3431":{
      "scriptId":"u35"},
    "1e5db5c0e1d54d46b6fbbc522afb2458":{
      "scriptId":"u36"},
    "d7f088ed050f49f5bcabd5fcc985017e":{
      "scriptId":"u37"},
    "ac2cf7d2bd5c4a3a868038cdada2dbbe":{
      "scriptId":"u38"},
    "e68f42f9ad4442919514f4cb8a0412a3":{
      "scriptId":"u39"},
    "e48b6df3eac24db6ae9311e3abde5222":{
      "scriptId":"u40"},
    "f3b564b17f07480683839a1025e62ea8":{
      "scriptId":"u41"},
    "23478d69837244e9b4e765f4bb702898":{
      "scriptId":"u42"},
    "62bfcf0ab37d472c9503fdb9439546b8":{
      "scriptId":"u43"},
    "0bb420b2564b41f0bb1a1a392def14ce":{
      "scriptId":"u44"},
    "054d15be71d5433baa85f0b50f0cd54e":{
      "scriptId":"u45"},
    "bdaae79761424fbaa2dd8255f20c9aa8":{
      "scriptId":"u46"},
    "fe2cbbc5b8494c5f8b939965049f1342":{
      "scriptId":"u47"},
    "51791c2558864742a180a0832784a2b6":{
      "scriptId":"u48"},
    "0dbc9b109b014e14930fb1844c1e541c":{
      "scriptId":"u49"},
    "5b5ca6a4c5ad47438e7a64be2598d0cf":{
      "scriptId":"u50"},
    "5ea1aa4e807746028db7ce28a82264de":{
      "scriptId":"u51"},
    "a5468a2e0a8b40238c22775ae524ca89":{
      "scriptId":"u52"},
    "ea95bb1fbe464749ba9e78a5d5c36b8d":{
      "scriptId":"u53"},
    "1c142b36011b47378a2f51852bbf301b":{
      "scriptId":"u54"},
    "f365a39f6215430ea8f75eb0b6c34873":{
      "scriptId":"u55"}}});