$axure.loadCurrentPage({
  "url":"颜色.html",
  "generationDate":new Date(1414911756879.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9feeb25f1a214b33ada06bce646c71f5",
    "type":"Axure:Page",
    "name":"颜色",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"139ce96a752d444296cebdde0648fd79",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFE6E49},
            "location":{
              "x":40,
              "y":40},
            "size":{
              "width":200,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5813ac7c2c043e3a262f2d0ec1a6ada",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFE6E49},
                "location":{
                  "x":40,
                  "y":40},
                "size":{
                  "width":200,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFE6E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/颜色/u0.png"}},
{
          "id":"bd4b46dd91684c1d8c76e2b9defccf5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFEAEAEA},
            "location":{
              "x":40,
              "y":160},
            "size":{
              "width":200,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d88255273964e808f952cd26d8bea98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEAEAEA},
                "location":{
                  "x":40,
                  "y":160},
                "size":{
                  "width":200,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEAEAEA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/颜色/u2.png"}},
{
          "id":"ee8f0de8f6b64291be6935d7781208c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0BAA9E},
            "location":{
              "x":40,
              "y":280},
            "size":{
              "width":200,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0BAA8E}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a297bea0ac94b3d9a1986c849566647",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0BAA9E},
                "location":{
                  "x":40,
                  "y":280},
                "size":{
                  "width":200,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0BAA8E}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/颜色/u4.png"}},
{
          "id":"2e330341852c4cffa46ceb0f24e38e7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFEB4F21},
            "location":{
              "x":270,
              "y":40},
            "size":{
              "width":200,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEB4F21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e83e4f4fb931413eaa71d7180269b5f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEB4F21},
                "location":{
                  "x":270,
                  "y":40},
                "size":{
                  "width":200,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEB4F21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/颜色/u6.png"}},
{
          "id":"e18ecc8e5a6f487bb8801dbda130ec46",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF00},
            "location":{
              "x":270,
              "y":280},
            "size":{
              "width":200,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51e3511f1e194cd196e93f6b40a2dc2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF00},
                "location":{
                  "x":270,
                  "y":280},
                "size":{
                  "width":200,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/颜色/u8.png"}},
{
          "id":"6f77b6cdcadc41a2a7fbcae3b234135d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":270,
              "y":160},
            "size":{
              "width":200,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4f75f4fcb01432aa41f7ffc5dccbf3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":270,
                  "y":160},
                "size":{
                  "width":200,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/颜色/u10.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "139ce96a752d444296cebdde0648fd79":{
      "scriptId":"u0"},
    "d5813ac7c2c043e3a262f2d0ec1a6ada":{
      "scriptId":"u1"},
    "bd4b46dd91684c1d8c76e2b9defccf5e":{
      "scriptId":"u2"},
    "9d88255273964e808f952cd26d8bea98":{
      "scriptId":"u3"},
    "ee8f0de8f6b64291be6935d7781208c1":{
      "scriptId":"u4"},
    "3a297bea0ac94b3d9a1986c849566647":{
      "scriptId":"u5"},
    "2e330341852c4cffa46ceb0f24e38e7e":{
      "scriptId":"u6"},
    "e83e4f4fb931413eaa71d7180269b5f0":{
      "scriptId":"u7"},
    "e18ecc8e5a6f487bb8801dbda130ec46":{
      "scriptId":"u8"},
    "51e3511f1e194cd196e93f6b40a2dc2c":{
      "scriptId":"u9"},
    "6f77b6cdcadc41a2a7fbcae3b234135d":{
      "scriptId":"u10"},
    "d4f75f4fcb01432aa41f7ffc5dccbf3b":{
      "scriptId":"u11"}}});