$axure.loadCurrentPage({
  "url":"用户列表条目.html",
  "generationDate":new Date(1414911757256.51),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e6a7b1ecd991409280149d9f71261f65",
    "type":"Axure:Page",
    "name":"用户列表条目",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dc21b461d9244bc2beadacd74b3ced82",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":720,
              "height":186},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adc2258e57c547809d4e4f27965660f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":720,
                  "height":186},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘列表条目/u17.png"}},
{
          "id":"e618ceff63d14a358bc9159e8f92acb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":150,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4aa2efab14e04a61a76a0359b1dc8c1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":150,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘列表条目/u19.png"}},
{
          "id":"a9d5bbd9cfc24c02a8337155d548488d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":200,
              "y":20},
            "size":{
              "width":57,
              "height":33},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43910c20ca5d4c51a3241c17297c7446",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":200,
                  "y":20},
                "size":{
                  "width":57,
                  "height":33},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10c080fb7bae4936a1e4d068f9e3b0db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Light', '微软雅黑'",
            "fontSize":"24px",
            "fontWeight":"290",
            "location":{
              "x":287,
              "y":22},
            "size":{
              "width":103,
              "height":31},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"838f4a2dab8d4af7bef93a03bd9cfff7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Light', '微软雅黑'",
                "fontSize":"24px",
                "fontWeight":"290",
                "location":{
                  "x":287,
                  "y":22},
                "size":{
                  "width":103,
                  "height":31},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eefd1d846eea49aeaea7f8884d53db2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":200,
              "y":135},
            "size":{
              "width":243,
              "height":34},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"058481a0905a4efd81f99553e44ba273",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":135},
                "size":{
                  "width":243,
                  "height":34},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4997f813c7e642b5b2b6c9b40d50ea00",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":640,
              "y":26},
            "size":{
              "width":54,
              "height":29},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1aa0c8a873c4407e894e115589db3fd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":640,
                  "y":26},
                "size":{
                  "width":54,
                  "height":29},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd852f36f4e847d5a5962c11a02de072",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":179},
            "size":{
              "width":520,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/招聘列表条目/u33_line.png"}},
{
          "id":"419a59104b6d43b495ac20625022de12",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF4D4D4D,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "location":{
              "x":594,
              "y":69},
            "size":{
              "width":100,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDDDDDD}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccf8266f47cb49d1af0b5f026a719658",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF4D4D4D,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "location":{
                  "x":594,
                  "y":69},
                "size":{
                  "width":100,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户列表条目/u13.png"}},
{
          "id":"810b97fb7a45421485f34513ccd030a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Light', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"290",
            "location":{
              "x":200,
              "y":100},
            "size":{
              "width":340,
              "height":24},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2885ea900ba84b6ea2bbe6f5d4513fa0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Light', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"290",
                "location":{
                  "x":200,
                  "y":100},
                "size":{
                  "width":340,
                  "height":24},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bafb57442eb44ea8a5996b99e50595af",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":200,
              "y":63},
            "size":{
              "width":63,
              "height":27},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9543a635ac4410992ed1b81144a8fd7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":200,
                  "y":63},
                "size":{
                  "width":63,
                  "height":27},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "dc21b461d9244bc2beadacd74b3ced82":{
      "scriptId":"u0"},
    "adc2258e57c547809d4e4f27965660f0":{
      "scriptId":"u1"},
    "e618ceff63d14a358bc9159e8f92acb4":{
      "scriptId":"u2"},
    "4aa2efab14e04a61a76a0359b1dc8c1d":{
      "scriptId":"u3"},
    "a9d5bbd9cfc24c02a8337155d548488d":{
      "scriptId":"u4"},
    "43910c20ca5d4c51a3241c17297c7446":{
      "scriptId":"u5"},
    "10c080fb7bae4936a1e4d068f9e3b0db":{
      "scriptId":"u6"},
    "838f4a2dab8d4af7bef93a03bd9cfff7":{
      "scriptId":"u7"},
    "eefd1d846eea49aeaea7f8884d53db2d":{
      "scriptId":"u8"},
    "058481a0905a4efd81f99553e44ba273":{
      "scriptId":"u9"},
    "4997f813c7e642b5b2b6c9b40d50ea00":{
      "scriptId":"u10"},
    "1aa0c8a873c4407e894e115589db3fd1":{
      "scriptId":"u11"},
    "dd852f36f4e847d5a5962c11a02de072":{
      "scriptId":"u12"},
    "419a59104b6d43b495ac20625022de12":{
      "scriptId":"u13"},
    "ccf8266f47cb49d1af0b5f026a719658":{
      "scriptId":"u14"},
    "810b97fb7a45421485f34513ccd030a2":{
      "scriptId":"u15"},
    "2885ea900ba84b6ea2bbe6f5d4513fa0":{
      "scriptId":"u16"},
    "bafb57442eb44ea8a5996b99e50595af":{
      "scriptId":"u17"},
    "f9543a635ac4410992ed1b81144a8fd7":{
      "scriptId":"u18"}}});