$axure.loadCurrentPage({
  "url":"提示框.html",
  "generationDate":new Date(1414911757131.41),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"765961d83b884a61b6db20330caa7ac4",
    "type":"Axure:Page",
    "name":"提示框",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c152cb58649d459eae8ae1976df411a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF2A2A2A},
            "location":{
              "x":20,
              "y":30},
            "size":{
              "width":570,
              "height":70},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":10,
              "color":{
                "r":153,
                "g":153,
                "b":153,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"876b27614294443b98d6ef9b5cd3f591",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF2A2A2A},
                "location":{
                  "x":20,
                  "y":30},
                "size":{
                  "width":570,
                  "height":70},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":10,
                  "color":{
                    "r":153,
                    "g":153,
                    "b":153,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提示框/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c152cb58649d459eae8ae1976df411a5":{
      "scriptId":"u0"},
    "876b27614294443b98d6ef9b5cd3f591":{
      "scriptId":"u1"}}});