$axure.loadCurrentPage({
  "url":"主页_-_2.html",
  "generationDate":new Date(1414911759208.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a5ab87ffe95a4d26bd69e4352a909a9f",
    "type":"Axure:Page",
    "name":"主页 - 2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"34ff5bb1b03a4deab57531331a13ce99",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFCFCFC},
            "location":{
              "x":0,
              "y":-5},
            "size":{
              "width":720,
              "height":1280},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a07942863bb345e4ae6295a404a21bb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFCFCFC},
                "location":{
                  "x":0,
                  "y":-5},
                "size":{
                  "width":720,
                  "height":1280},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u0.png"}},
{
          "id":"a70e73c3716e48e091d6f1fd64ec992c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "size":{
              "width":720,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"039f76d016b44207b74a57c9770a7b44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "size":{
                  "width":720,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录界面/u10.png"}},
{
          "id":"a6c6c96ffbb3405fa10819c6a4b44ebc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Roboto Thin', 'Roboto'",
            "fontWeight":"250",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF8F8FA,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":642,
              "y":10},
            "size":{
              "width":51,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7e5c2d7038546238a823d7dc2438cd7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Thin', 'Roboto'",
                "fontWeight":"250",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF8F8FA,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":642,
                  "y":10},
                "size":{
                  "width":51,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u12.png"}},
{
          "id":"28ac43c3906c4178aea5f8b4129f6b49",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":604,
              "y":23},
            "size":{
              "width":18,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF8F8FA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69a4fd8049e84763a0d15b4e0c302756",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":604,
                  "y":23},
                "size":{
                  "width":18,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF8F8FA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u14.png"}},
{
          "id":"9822acbad764447f9c1d4db22544b53e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":604,
              "y":11},
            "size":{
              "width":18,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC6C6C6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"159a7ae28fdc4af2b31bf5a9f71dd2ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":604,
                  "y":11},
                "size":{
                  "width":18,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC6C6C6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u16.png"}},
{
          "id":"fc74e7cc080b4e56866e0b6859df6807",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":608,
              "y":9},
            "size":{
              "width":8,
              "height":2},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC6C6C6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"635571b88e2f454b9e6ff90ad3df1eee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":608,
                  "y":9},
                "size":{
                  "width":8,
                  "height":2},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC6C6C6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u18.png"}},
{
          "id":"1bc841bf4ed2454591f9c501d3dcd77f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":0,
              "y":48},
            "size":{
              "width":720,
              "height":100},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edc10123a66047a18a3f9821934535ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":0,
                  "y":48},
                "size":{
                  "width":720,
                  "height":100},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航栏/u0.png"}},
{
          "id":"5092295a82144f43b724c48aca4b9369",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":97,
              "y":79},
            "size":{
              "width":145,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5dc2c24553144ac888bb20b828d297f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":97,
                  "y":79},
                "size":{
                  "width":145,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_0/u14.png"}},
{
          "id":"ea4c21af11b241b88468b01361f60a79",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":75},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fcafc914b254651aa12ce4e64f783f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":75},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_0/u16.png"}},
{
          "id":"3ce43a31ab1d49be843cd0d52f92b21b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":575,
              "y":73},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abcea9298d8b44d79a5365083a81caa4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":575,
                  "y":73},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_0/u18.png"}},
{
          "id":"63f56ff05f284c1d8093c05239ea8c7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":0,
              "y":148},
            "size":{
              "width":360,
              "height":100},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fd5883e12f846a8ac473540817a08cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":0,
                  "y":148},
                "size":{
                  "width":360,
                  "height":100},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_0/u20.png"}},
{
          "id":"d84da392cd0046b2be789e6576ed3dc5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":360,
              "y":148},
            "size":{
              "width":360,
              "height":100},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b78cb6dfcbd442f28a93d9d61b1c75eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":360,
                  "y":148},
                "size":{
                  "width":360,
                  "height":100},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_0/u20.png"}},
{
          "id":"09576528b22c4ec4bfd4c44076270c26",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF00},
            "location":{
              "x":360,
              "y":238},
            "size":{
              "width":360,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"168c814fa8b84fd586d64964385bf72d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF00},
                "location":{
                  "x":360,
                  "y":238},
                "size":{
                  "width":360,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_0/u24.png"}},
{
          "id":"c63b5184fd8d4fefb954801d63bf6161",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":0,
              "y":1182},
            "size":{
              "width":720,
              "height":98},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c1a5114f95045d2903737c690aad57d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":0,
                  "y":1182},
                "size":{
                  "width":720,
                  "height":98},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u2.png"}},
{
          "id":"8e1428c479a44cbfb14c47fc68fd48d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":137,
              "y":1206},
            "size":{
              "width":42,
              "height":50},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA2A2A2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9de259ccd904db9a3578bd5d962f7c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":137,
                  "y":1206},
                "size":{
                  "width":42,
                  "height":50},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA2A2A2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u4.png"}},
{
          "id":"786bfa9a82664b46975b0cc478f74573",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":335,
              "y":1206},
            "size":{
              "width":50,
              "height":50},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA2A2A2},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9ee47dcaf6b412a9745107705266061",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":335,
                  "y":1206},
                "size":{
                  "width":50,
                  "height":50},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA2A2A2},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u6.png"}},
{
          "id":"e75828a0ee7a497ea66d336378876673",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":541,
              "y":1209},
            "size":{
              "width":44,
              "height":44},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA2A2A2},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df489a7eeb3b4e85874065a934830cc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":541,
                  "y":1209},
                "size":{
                  "width":44,
                  "height":44},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA2A2A2},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u8.png"}},
{
          "id":"ed0ec367251247f794d52306b9fcce8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":248},
            "size":{
              "width":720,
              "height":186},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6070051abe974630a4721f0b442e51db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":248},
                "size":{
                  "width":720,
                  "height":186},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘列表条目/u17.png"}},
{
          "id":"f2bf035d996541d58744817d3a91be02",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":20,
              "y":268},
            "size":{
              "width":150,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cc6d3e29a4742e59fea8ed646329dd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":20,
                  "y":268},
                "size":{
                  "width":150,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_1/u36.png"}},
{
          "id":"488e87e801f64edeb25af30467b722e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":200,
              "y":268},
            "size":{
              "width":57,
              "height":33},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"158ac5540ad74314be61315e6099f4c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":200,
                  "y":268},
                "size":{
                  "width":57,
                  "height":33},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"07b9147b4eaa46b7b377613c973bf005",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Light', '微软雅黑'",
            "fontSize":"24px",
            "fontWeight":"290",
            "location":{
              "x":287,
              "y":270},
            "size":{
              "width":103,
              "height":31},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df66361d252f4a0ca26309be2ea39aab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Light', '微软雅黑'",
                "fontSize":"24px",
                "fontWeight":"290",
                "location":{
                  "x":287,
                  "y":270},
                "size":{
                  "width":103,
                  "height":31},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6551d4b52d454e84a1aeac3b65960068",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":200,
              "y":383},
            "size":{
              "width":243,
              "height":34},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"535f2bb21e7b4e2f83a163dfaa72c7f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":383},
                "size":{
                  "width":243,
                  "height":34},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a323ef9483f344f991348ea97af35246",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":640,
              "y":274},
            "size":{
              "width":54,
              "height":29},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca9ca6bf89e349d49a663ee476d2cd01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":640,
                  "y":274},
                "size":{
                  "width":54,
                  "height":29},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba6894f0fcbc447e8ba542101146af9a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":427},
            "size":{
              "width":520,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/招聘列表条目/u33_line.png"}},
{
          "id":"7983269cb09e4c5ebb866b2ab17f0771",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFE6E49,
              "opacity":1},
            "location":{
              "x":575,
              "y":317},
            "size":{
              "width":119,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"725fb804285c4f159b377f751497fa5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFE6E49,
                  "opacity":1},
                "location":{
                  "x":575,
                  "y":317},
                "size":{
                  "width":119,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_2/u47.png"}},
{
          "id":"15ccb079bddf4956a6f9f8911047d96c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Light', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"290",
            "location":{
              "x":200,
              "y":348},
            "size":{
              "width":340,
              "height":24},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f8700c781464bb59281a84a07a50f79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Light', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"290",
                "location":{
                  "x":200,
                  "y":348},
                "size":{
                  "width":340,
                  "height":24},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cad93ce5e653463d8c967a7c46dce73e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":200,
              "y":311},
            "size":{
              "width":63,
              "height":27},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88311151909843049e54a1eae2f85fc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":200,
                  "y":311},
                "size":{
                  "width":63,
                  "height":27},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d2c3c9168dd4cbbb245ab07e1fda9e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":434},
            "size":{
              "width":720,
              "height":186},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5cf68d1365e4edda38ac05741e1f8e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":434},
                "size":{
                  "width":720,
                  "height":186},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘列表条目/u17.png"}},
{
          "id":"ed26034b0301475e867ea9af33640842",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":20,
              "y":454},
            "size":{
              "width":150,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3154d8de6fcd46cfacb4c01297c954bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":20,
                  "y":454},
                "size":{
                  "width":150,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_1/u36.png"}},
{
          "id":"fcf0a0eddebc4d9c9e670847e633a10a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":200,
              "y":454},
            "size":{
              "width":57,
              "height":33},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"674f37252e1f41b792d95aa0a6b3c555",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":200,
                  "y":454},
                "size":{
                  "width":57,
                  "height":33},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3873b91faaa8406e8984becb5edb4bf5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Light', '微软雅黑'",
            "fontSize":"24px",
            "fontWeight":"290",
            "location":{
              "x":287,
              "y":456},
            "size":{
              "width":103,
              "height":31},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a07527bc6b8f4573b2893d8eeb9d2cac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Light', '微软雅黑'",
                "fontSize":"24px",
                "fontWeight":"290",
                "location":{
                  "x":287,
                  "y":456},
                "size":{
                  "width":103,
                  "height":31},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2efc96f379f4107a1e80c83adec4976",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":200,
              "y":569},
            "size":{
              "width":212,
              "height":34},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b5765a341e64fa0b1f2c2bc77226918",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":569},
                "size":{
                  "width":212,
                  "height":34},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e80933d67d674c8d9e55b7158aa65c5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":640,
              "y":460},
            "size":{
              "width":54,
              "height":29},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7042aca406a4503aa8b9ce74f04307e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":640,
                  "y":460},
                "size":{
                  "width":54,
                  "height":29},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b431c75669394883b233083477db0106",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":613},
            "size":{
              "width":520,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/招聘列表条目/u33_line.png"}},
{
          "id":"10ba0ddb4ccf47c19cbdda137c1c02a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFE6E49,
              "opacity":1},
            "location":{
              "x":575,
              "y":503},
            "size":{
              "width":119,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be281b30fcc24f67b8d28a145c800ac6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFE6E49,
                  "opacity":1},
                "location":{
                  "x":575,
                  "y":503},
                "size":{
                  "width":119,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_2/u47.png"}},
{
          "id":"d716a31ffbd644b58559550c40cd045e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Light', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"290",
            "location":{
              "x":200,
              "y":534},
            "size":{
              "width":340,
              "height":24},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea7c3b5b474c4be88da5cb9c0c4f3c74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Light', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"290",
                "location":{
                  "x":200,
                  "y":534},
                "size":{
                  "width":340,
                  "height":24},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"779faa7a166349e299a723b7ff555e87",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":200,
              "y":497},
            "size":{
              "width":63,
              "height":27},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcfd464343864bcda382a7819e5c4b92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":200,
                  "y":497},
                "size":{
                  "width":63,
                  "height":27},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9bea73baca534a1585b39c6ba50fa9f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":620},
            "size":{
              "width":720,
              "height":186},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"806829ef80f943f2abc9a8e471fc807e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":620},
                "size":{
                  "width":720,
                  "height":186},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘列表条目/u17.png"}},
{
          "id":"ac8b0cb30d384a46a58952f283d40d14",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":20,
              "y":640},
            "size":{
              "width":150,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ccc63920c4d479ab60b64025b68a538",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":20,
                  "y":640},
                "size":{
                  "width":150,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_1/u36.png"}},
{
          "id":"c2b884edf3af4b0d8ad6ad59195fd16b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":200,
              "y":640},
            "size":{
              "width":57,
              "height":33},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33d2e01b0346426ea741cc6765aefe5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":200,
                  "y":640},
                "size":{
                  "width":57,
                  "height":33},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee0e671b3f7d453fbe69435a208e4cd9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Light', '微软雅黑'",
            "fontSize":"24px",
            "fontWeight":"290",
            "location":{
              "x":287,
              "y":642},
            "size":{
              "width":103,
              "height":31},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3feb0f9c006442bf8fb4abe524ea9d81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Light', '微软雅黑'",
                "fontSize":"24px",
                "fontWeight":"290",
                "location":{
                  "x":287,
                  "y":642},
                "size":{
                  "width":103,
                  "height":31},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1fc9739ae47e43b585866cb8237251d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":200,
              "y":755},
            "size":{
              "width":221,
              "height":34},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"896d76a575e549b98140eb6968afc3b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":755},
                "size":{
                  "width":221,
                  "height":34},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"052a38f15fdc4c458e81657f74b9f8eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":640,
              "y":646},
            "size":{
              "width":54,
              "height":29},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23aa6a50e3a84c67b531d049daf9272a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":640,
                  "y":646},
                "size":{
                  "width":54,
                  "height":29},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5882939ac65b4f56bf4802ddf74790f1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":799},
            "size":{
              "width":520,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/招聘列表条目/u33_line.png"}},
{
          "id":"7122c74aaf944f44bdd383d20f7cee72",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA,
              "opacity":1},
            "location":{
              "x":575,
              "y":689},
            "size":{
              "width":119,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e0822fcbc1d4313bdb4c0e21febe744",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFEAEAEA,
                  "opacity":1},
                "location":{
                  "x":575,
                  "y":689},
                "size":{
                  "width":119,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEAEAEA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_2/u85.png"}},
{
          "id":"d49284984e034971b2edec9d2b248aeb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Light', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"290",
            "location":{
              "x":200,
              "y":720},
            "size":{
              "width":340,
              "height":24},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e08162842b84c018a940bd0ab6e3bd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Light', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"290",
                "location":{
                  "x":200,
                  "y":720},
                "size":{
                  "width":340,
                  "height":24},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5dd9964b3a84249955b88cf4ff6644f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":200,
              "y":683},
            "size":{
              "width":63,
              "height":27},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"631e3103376747ab904b5c780c4b7183",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":200,
                  "y":683},
                "size":{
                  "width":63,
                  "height":27},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"971fa1150435450baa240d4f67ebb7d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":806},
            "size":{
              "width":720,
              "height":186},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ae1a3a3d9634e8899ad15a15fbc1683",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":806},
                "size":{
                  "width":720,
                  "height":186},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘列表条目/u17.png"}},
{
          "id":"588e31a8265445bcb9f52876fc132f5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":20,
              "y":826},
            "size":{
              "width":150,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da18e8b087434b56a9c4b5c216927a61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":20,
                  "y":826},
                "size":{
                  "width":150,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_1/u36.png"}},
{
          "id":"2115b4249c2f4e828a37a1d87e126348",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":200,
              "y":826},
            "size":{
              "width":57,
              "height":33},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44ad728a6a5d4c4cb8ac0046beecd59b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":200,
                  "y":826},
                "size":{
                  "width":57,
                  "height":33},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a0fa8cd1a464f6795ad01cf8e87ac04",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Light', '微软雅黑'",
            "fontSize":"24px",
            "fontWeight":"290",
            "location":{
              "x":288,
              "y":828},
            "size":{
              "width":103,
              "height":31},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9847c2addc7640d69361f6f67c72e721",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Light', '微软雅黑'",
                "fontSize":"24px",
                "fontWeight":"290",
                "location":{
                  "x":288,
                  "y":828},
                "size":{
                  "width":103,
                  "height":31},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77e080e133d247db8d2190e511296533",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":200,
              "y":941},
            "size":{
              "width":223,
              "height":34},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14a9dd59b5d4409680eed5d6658c2fbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":941},
                "size":{
                  "width":223,
                  "height":34},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b19b53b5faf4528a9c75e8e429d9e2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":640,
              "y":832},
            "size":{
              "width":54,
              "height":29},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c5acb512e344ca2a846cf99f1151cc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":640,
                  "y":832},
                "size":{
                  "width":54,
                  "height":29},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35a4f5de4e3b4a659ff8319aad1ffbd9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":985},
            "size":{
              "width":520,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/招聘列表条目/u33_line.png"}},
{
          "id":"f281034ac0fe4de78331a884cc4d4847",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFE6E49,
              "opacity":1},
            "location":{
              "x":575,
              "y":875},
            "size":{
              "width":119,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a916be149fe0447281e15bfbf0d85734",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFE6E49,
                  "opacity":1},
                "location":{
                  "x":575,
                  "y":875},
                "size":{
                  "width":119,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_2/u47.png"}},
{
          "id":"3c569987f8394fab950d6b30821fb873",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Light', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"290",
            "location":{
              "x":200,
              "y":906},
            "size":{
              "width":340,
              "height":24},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d902673f70a44c5a9387251efab381d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Light', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"290",
                "location":{
                  "x":200,
                  "y":906},
                "size":{
                  "width":340,
                  "height":24},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e1dc462766974e05be9397983f85a283",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":200,
              "y":869},
            "size":{
              "width":63,
              "height":27},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1728e8ea658343b4949fb41b89237f1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":200,
                  "y":869},
                "size":{
                  "width":63,
                  "height":27},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f4f9e77eadf481abee3b199e790264c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":992},
            "size":{
              "width":720,
              "height":186},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f18e0a348ad4c57a0aa246edbda83e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":992},
                "size":{
                  "width":720,
                  "height":186},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘列表条目/u17.png"}},
{
          "id":"e925c443628c450a80e3c7e99073da98",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":20,
              "y":1012},
            "size":{
              "width":150,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a865d238979e4c3eabc06c0d9dc2b87f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":20,
                  "y":1012},
                "size":{
                  "width":150,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_1/u36.png"}},
{
          "id":"6efc053509d441ff98262be26b8fd932",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":200,
              "y":1012},
            "size":{
              "width":57,
              "height":33},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30e54153eeaf4611882ea79f3687f6ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":200,
                  "y":1012},
                "size":{
                  "width":57,
                  "height":33},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a9c5204105c844b8bb0abb01b2e03106",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Light', '微软雅黑'",
            "fontSize":"24px",
            "fontWeight":"290",
            "location":{
              "x":287,
              "y":1014},
            "size":{
              "width":103,
              "height":31},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07ae51d962464164af2579805fca2892",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Light', '微软雅黑'",
                "fontSize":"24px",
                "fontWeight":"290",
                "location":{
                  "x":287,
                  "y":1014},
                "size":{
                  "width":103,
                  "height":31},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0db22eda4f224554b164daa73d74ce02",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":200,
              "y":1127},
            "size":{
              "width":192,
              "height":34},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90dd1962b2074fc6855dcf4c25a58b06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":1127},
                "size":{
                  "width":192,
                  "height":34},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"60d31f7b73e44485b9a229021600a810",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":640,
              "y":1018},
            "size":{
              "width":54,
              "height":29},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"747901ca7154499ca83dd548dfed5f73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":640,
                  "y":1018},
                "size":{
                  "width":54,
                  "height":29},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad468e6589194b7dbfaed365d539d90a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":1171},
            "size":{
              "width":520,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/招聘列表条目/u33_line.png"}},
{
          "id":"b0346a0a87304e08bba36c1ff97cae8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA,
              "opacity":1},
            "location":{
              "x":575,
              "y":1061},
            "size":{
              "width":119,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"506e3338d5b84e34ade7059d7e2d4f9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFEAEAEA,
                  "opacity":1},
                "location":{
                  "x":575,
                  "y":1061},
                "size":{
                  "width":119,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEAEAEA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_2/u85.png"}},
{
          "id":"f0c0a2ae3d814b388e03b0e11b73e246",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Light', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"290",
            "location":{
              "x":200,
              "y":1092},
            "size":{
              "width":340,
              "height":24},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"397a9b0cdf88425e82f8565a7bae5c23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Light', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"290",
                "location":{
                  "x":200,
                  "y":1092},
                "size":{
                  "width":340,
                  "height":24},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b5625c84a2c4c30907ddb293956931c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":200,
              "y":1055},
            "size":{
              "width":63,
              "height":27},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"229c9b8a018945f89b64bc9d348dd63e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":200,
                  "y":1055},
                "size":{
                  "width":63,
                  "height":27},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98ec375ce0ff4845a575a1405e67cab1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":645,
              "y":73},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2240d3648b0e453bbd61885f6a12690a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":645,
                  "y":73},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_0/u102.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "34ff5bb1b03a4deab57531331a13ce99":{
      "scriptId":"u0"},
    "a07942863bb345e4ae6295a404a21bb8":{
      "scriptId":"u1"},
    "a70e73c3716e48e091d6f1fd64ec992c":{
      "scriptId":"u2"},
    "039f76d016b44207b74a57c9770a7b44":{
      "scriptId":"u3"},
    "a6c6c96ffbb3405fa10819c6a4b44ebc":{
      "scriptId":"u4"},
    "e7e5c2d7038546238a823d7dc2438cd7":{
      "scriptId":"u5"},
    "28ac43c3906c4178aea5f8b4129f6b49":{
      "scriptId":"u6"},
    "69a4fd8049e84763a0d15b4e0c302756":{
      "scriptId":"u7"},
    "9822acbad764447f9c1d4db22544b53e":{
      "scriptId":"u8"},
    "159a7ae28fdc4af2b31bf5a9f71dd2ac":{
      "scriptId":"u9"},
    "fc74e7cc080b4e56866e0b6859df6807":{
      "scriptId":"u10"},
    "635571b88e2f454b9e6ff90ad3df1eee":{
      "scriptId":"u11"},
    "1bc841bf4ed2454591f9c501d3dcd77f":{
      "scriptId":"u12"},
    "edc10123a66047a18a3f9821934535ff":{
      "scriptId":"u13"},
    "5092295a82144f43b724c48aca4b9369":{
      "scriptId":"u14"},
    "d5dc2c24553144ac888bb20b828d297f":{
      "scriptId":"u15"},
    "ea4c21af11b241b88468b01361f60a79":{
      "scriptId":"u16"},
    "4fcafc914b254651aa12ce4e64f783f8":{
      "scriptId":"u17"},
    "3ce43a31ab1d49be843cd0d52f92b21b":{
      "scriptId":"u18"},
    "abcea9298d8b44d79a5365083a81caa4":{
      "scriptId":"u19"},
    "63f56ff05f284c1d8093c05239ea8c7f":{
      "scriptId":"u20"},
    "7fd5883e12f846a8ac473540817a08cf":{
      "scriptId":"u21"},
    "d84da392cd0046b2be789e6576ed3dc5":{
      "scriptId":"u22"},
    "b78cb6dfcbd442f28a93d9d61b1c75eb":{
      "scriptId":"u23"},
    "09576528b22c4ec4bfd4c44076270c26":{
      "scriptId":"u24"},
    "168c814fa8b84fd586d64964385bf72d":{
      "scriptId":"u25"},
    "c63b5184fd8d4fefb954801d63bf6161":{
      "scriptId":"u26"},
    "0c1a5114f95045d2903737c690aad57d":{
      "scriptId":"u27"},
    "8e1428c479a44cbfb14c47fc68fd48d5":{
      "scriptId":"u28"},
    "b9de259ccd904db9a3578bd5d962f7c8":{
      "scriptId":"u29"},
    "786bfa9a82664b46975b0cc478f74573":{
      "scriptId":"u30"},
    "c9ee47dcaf6b412a9745107705266061":{
      "scriptId":"u31"},
    "e75828a0ee7a497ea66d336378876673":{
      "scriptId":"u32"},
    "df489a7eeb3b4e85874065a934830cc8":{
      "scriptId":"u33"},
    "ed0ec367251247f794d52306b9fcce8f":{
      "scriptId":"u34"},
    "6070051abe974630a4721f0b442e51db":{
      "scriptId":"u35"},
    "f2bf035d996541d58744817d3a91be02":{
      "scriptId":"u36"},
    "7cc6d3e29a4742e59fea8ed646329dd0":{
      "scriptId":"u37"},
    "488e87e801f64edeb25af30467b722e7":{
      "scriptId":"u38"},
    "158ac5540ad74314be61315e6099f4c4":{
      "scriptId":"u39"},
    "07b9147b4eaa46b7b377613c973bf005":{
      "scriptId":"u40"},
    "df66361d252f4a0ca26309be2ea39aab":{
      "scriptId":"u41"},
    "6551d4b52d454e84a1aeac3b65960068":{
      "scriptId":"u42"},
    "535f2bb21e7b4e2f83a163dfaa72c7f6":{
      "scriptId":"u43"},
    "a323ef9483f344f991348ea97af35246":{
      "scriptId":"u44"},
    "ca9ca6bf89e349d49a663ee476d2cd01":{
      "scriptId":"u45"},
    "ba6894f0fcbc447e8ba542101146af9a":{
      "scriptId":"u46"},
    "7983269cb09e4c5ebb866b2ab17f0771":{
      "scriptId":"u47"},
    "725fb804285c4f159b377f751497fa5d":{
      "scriptId":"u48"},
    "15ccb079bddf4956a6f9f8911047d96c":{
      "scriptId":"u49"},
    "6f8700c781464bb59281a84a07a50f79":{
      "scriptId":"u50"},
    "cad93ce5e653463d8c967a7c46dce73e":{
      "scriptId":"u51"},
    "88311151909843049e54a1eae2f85fc5":{
      "scriptId":"u52"},
    "8d2c3c9168dd4cbbb245ab07e1fda9e1":{
      "scriptId":"u53"},
    "a5cf68d1365e4edda38ac05741e1f8e7":{
      "scriptId":"u54"},
    "ed26034b0301475e867ea9af33640842":{
      "scriptId":"u55"},
    "3154d8de6fcd46cfacb4c01297c954bd":{
      "scriptId":"u56"},
    "fcf0a0eddebc4d9c9e670847e633a10a":{
      "scriptId":"u57"},
    "674f37252e1f41b792d95aa0a6b3c555":{
      "scriptId":"u58"},
    "3873b91faaa8406e8984becb5edb4bf5":{
      "scriptId":"u59"},
    "a07527bc6b8f4573b2893d8eeb9d2cac":{
      "scriptId":"u60"},
    "f2efc96f379f4107a1e80c83adec4976":{
      "scriptId":"u61"},
    "0b5765a341e64fa0b1f2c2bc77226918":{
      "scriptId":"u62"},
    "e80933d67d674c8d9e55b7158aa65c5e":{
      "scriptId":"u63"},
    "d7042aca406a4503aa8b9ce74f04307e":{
      "scriptId":"u64"},
    "b431c75669394883b233083477db0106":{
      "scriptId":"u65"},
    "10ba0ddb4ccf47c19cbdda137c1c02a9":{
      "scriptId":"u66"},
    "be281b30fcc24f67b8d28a145c800ac6":{
      "scriptId":"u67"},
    "d716a31ffbd644b58559550c40cd045e":{
      "scriptId":"u68"},
    "ea7c3b5b474c4be88da5cb9c0c4f3c74":{
      "scriptId":"u69"},
    "779faa7a166349e299a723b7ff555e87":{
      "scriptId":"u70"},
    "bcfd464343864bcda382a7819e5c4b92":{
      "scriptId":"u71"},
    "9bea73baca534a1585b39c6ba50fa9f5":{
      "scriptId":"u72"},
    "806829ef80f943f2abc9a8e471fc807e":{
      "scriptId":"u73"},
    "ac8b0cb30d384a46a58952f283d40d14":{
      "scriptId":"u74"},
    "9ccc63920c4d479ab60b64025b68a538":{
      "scriptId":"u75"},
    "c2b884edf3af4b0d8ad6ad59195fd16b":{
      "scriptId":"u76"},
    "33d2e01b0346426ea741cc6765aefe5a":{
      "scriptId":"u77"},
    "ee0e671b3f7d453fbe69435a208e4cd9":{
      "scriptId":"u78"},
    "3feb0f9c006442bf8fb4abe524ea9d81":{
      "scriptId":"u79"},
    "1fc9739ae47e43b585866cb8237251d7":{
      "scriptId":"u80"},
    "896d76a575e549b98140eb6968afc3b7":{
      "scriptId":"u81"},
    "052a38f15fdc4c458e81657f74b9f8eb":{
      "scriptId":"u82"},
    "23aa6a50e3a84c67b531d049daf9272a":{
      "scriptId":"u83"},
    "5882939ac65b4f56bf4802ddf74790f1":{
      "scriptId":"u84"},
    "7122c74aaf944f44bdd383d20f7cee72":{
      "scriptId":"u85"},
    "5e0822fcbc1d4313bdb4c0e21febe744":{
      "scriptId":"u86"},
    "d49284984e034971b2edec9d2b248aeb":{
      "scriptId":"u87"},
    "8e08162842b84c018a940bd0ab6e3bd9":{
      "scriptId":"u88"},
    "a5dd9964b3a84249955b88cf4ff6644f":{
      "scriptId":"u89"},
    "631e3103376747ab904b5c780c4b7183":{
      "scriptId":"u90"},
    "971fa1150435450baa240d4f67ebb7d2":{
      "scriptId":"u91"},
    "8ae1a3a3d9634e8899ad15a15fbc1683":{
      "scriptId":"u92"},
    "588e31a8265445bcb9f52876fc132f5e":{
      "scriptId":"u93"},
    "da18e8b087434b56a9c4b5c216927a61":{
      "scriptId":"u94"},
    "2115b4249c2f4e828a37a1d87e126348":{
      "scriptId":"u95"},
    "44ad728a6a5d4c4cb8ac0046beecd59b":{
      "scriptId":"u96"},
    "7a0fa8cd1a464f6795ad01cf8e87ac04":{
      "scriptId":"u97"},
    "9847c2addc7640d69361f6f67c72e721":{
      "scriptId":"u98"},
    "77e080e133d247db8d2190e511296533":{
      "scriptId":"u99"},
    "14a9dd59b5d4409680eed5d6658c2fbf":{
      "scriptId":"u100"},
    "1b19b53b5faf4528a9c75e8e429d9e2c":{
      "scriptId":"u101"},
    "9c5acb512e344ca2a846cf99f1151cc1":{
      "scriptId":"u102"},
    "35a4f5de4e3b4a659ff8319aad1ffbd9":{
      "scriptId":"u103"},
    "f281034ac0fe4de78331a884cc4d4847":{
      "scriptId":"u104"},
    "a916be149fe0447281e15bfbf0d85734":{
      "scriptId":"u105"},
    "3c569987f8394fab950d6b30821fb873":{
      "scriptId":"u106"},
    "d902673f70a44c5a9387251efab381d2":{
      "scriptId":"u107"},
    "e1dc462766974e05be9397983f85a283":{
      "scriptId":"u108"},
    "1728e8ea658343b4949fb41b89237f1d":{
      "scriptId":"u109"},
    "5f4f9e77eadf481abee3b199e790264c":{
      "scriptId":"u110"},
    "6f18e0a348ad4c57a0aa246edbda83e8":{
      "scriptId":"u111"},
    "e925c443628c450a80e3c7e99073da98":{
      "scriptId":"u112"},
    "a865d238979e4c3eabc06c0d9dc2b87f":{
      "scriptId":"u113"},
    "6efc053509d441ff98262be26b8fd932":{
      "scriptId":"u114"},
    "30e54153eeaf4611882ea79f3687f6ff":{
      "scriptId":"u115"},
    "a9c5204105c844b8bb0abb01b2e03106":{
      "scriptId":"u116"},
    "07ae51d962464164af2579805fca2892":{
      "scriptId":"u117"},
    "0db22eda4f224554b164daa73d74ce02":{
      "scriptId":"u118"},
    "90dd1962b2074fc6855dcf4c25a58b06":{
      "scriptId":"u119"},
    "60d31f7b73e44485b9a229021600a810":{
      "scriptId":"u120"},
    "747901ca7154499ca83dd548dfed5f73":{
      "scriptId":"u121"},
    "ad468e6589194b7dbfaed365d539d90a":{
      "scriptId":"u122"},
    "b0346a0a87304e08bba36c1ff97cae8e":{
      "scriptId":"u123"},
    "506e3338d5b84e34ade7059d7e2d4f9e":{
      "scriptId":"u124"},
    "f0c0a2ae3d814b388e03b0e11b73e246":{
      "scriptId":"u125"},
    "397a9b0cdf88425e82f8565a7bae5c23":{
      "scriptId":"u126"},
    "4b5625c84a2c4c30907ddb293956931c":{
      "scriptId":"u127"},
    "229c9b8a018945f89b64bc9d348dd63e":{
      "scriptId":"u128"},
    "98ec375ce0ff4845a575a1405e67cab1":{
      "scriptId":"u129"},
    "2240d3648b0e453bbd61885f6a12690a":{
      "scriptId":"u130"}}});