$axure.loadCurrentPage({
  "url":"主页_-_0.html",
  "generationDate":new Date(1414911758836.53),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"172aef756fee46918766bcfc973b2170",
    "type":"Axure:Page",
    "name":"主页 - 0",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"11bd4ca700a5472babf0f942e0bff57c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFCFCFC},
            "location":{
              "x":0,
              "y":-5},
            "size":{
              "width":720,
              "height":1280},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"102e734053f24774ba06ba697d682e20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFCFCFC},
                "location":{
                  "x":0,
                  "y":-5},
                "size":{
                  "width":720,
                  "height":1280},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u0.png"}},
{
          "id":"10ba221f9c764491aee9766eda78e7dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "size":{
              "width":720,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b240c1403c8e4d809c553054311550fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "size":{
                  "width":720,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录界面/u10.png"}},
{
          "id":"1805d694bae54a328df0247d0097a044",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Roboto Thin', 'Roboto'",
            "fontWeight":"250",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF8F8FA,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":642,
              "y":10},
            "size":{
              "width":51,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a209a1e515f4a3e8011876282618cd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Thin', 'Roboto'",
                "fontWeight":"250",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF8F8FA,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":642,
                  "y":10},
                "size":{
                  "width":51,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u12.png"}},
{
          "id":"da7620abe4954f3a9100cfff871b8d9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":604,
              "y":23},
            "size":{
              "width":18,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF8F8FA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9891ed1612fc4fbaaa39c8acf4099504",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":604,
                  "y":23},
                "size":{
                  "width":18,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF8F8FA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u14.png"}},
{
          "id":"d97f3d3d8c7f49c99f09adeb8a2da9a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":604,
              "y":11},
            "size":{
              "width":18,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC6C6C6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97d72abbe40e4dd6a1489134b7d15c1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":604,
                  "y":11},
                "size":{
                  "width":18,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC6C6C6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u16.png"}},
{
          "id":"a9ce0e93e2194f5d9646a2200205bdfa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":608,
              "y":9},
            "size":{
              "width":8,
              "height":2},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC6C6C6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7135faaa5514e909a92f21e60e1fc3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":608,
                  "y":9},
                "size":{
                  "width":8,
                  "height":2},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC6C6C6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u18.png"}},
{
          "id":"8aee7f44637d40cc95e7d6b8acabab1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":0,
              "y":48},
            "size":{
              "width":720,
              "height":100},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bafc3c3802345dca2f2b7616d534906",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":0,
                  "y":48},
                "size":{
                  "width":720,
                  "height":100},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航栏/u0.png"}},
{
          "id":"f5a35e23e5414b0cad116d8456d505db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":97,
              "y":79},
            "size":{
              "width":145,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb9bdfa595164df789733792012b45fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":97,
                  "y":79},
                "size":{
                  "width":145,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_0/u14.png"}},
{
          "id":"841de535cb374b27af91ee5cf4133f92",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":75},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fe72daabbcb4108be31bcbebae5282f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":75},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_0/u16.png"}},
{
          "id":"d1ddd6193f8e4929820ef2874713bb0d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":575,
              "y":73},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6546a0250c841d79ca1f66444d85608",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":575,
                  "y":73},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_0/u18.png"}},
{
          "id":"5cf431329d36427fb9a3ac2bbcbeea4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":0,
              "y":148},
            "size":{
              "width":360,
              "height":100},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12806b4b006c434f9f2057bb6220f5a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":0,
                  "y":148},
                "size":{
                  "width":360,
                  "height":100},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_0/u20.png"}},
{
          "id":"d61333bcd24146c8b25d2f68715c6cd3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":360,
              "y":148},
            "size":{
              "width":360,
              "height":100},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad32268f71804c20936127a204c5b6dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":360,
                  "y":148},
                "size":{
                  "width":360,
                  "height":100},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_0/u20.png"}},
{
          "id":"c6ab52edd3ee42ae93c370e3c01c8a9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF00},
            "location":{
              "x":0,
              "y":238},
            "size":{
              "width":360,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81d6b352089e4746b11cfc6cb0135cc7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF00},
                "location":{
                  "x":0,
                  "y":238},
                "size":{
                  "width":360,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_0/u24.png"}},
{
          "id":"1e4e716952d84a8da28f562214cc0b20",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":248},
            "size":{
              "width":720,
              "height":240},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f57fedd4bee4f04a37a17ec67879893",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":248},
                "size":{
                  "width":720,
                  "height":240},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_0/u26.png"}},
{
          "id":"a21a26c36a134048a15d809bb3ba69fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":20,
              "y":268},
            "size":{
              "width":200,
              "height":200},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"793e81a82b9d44ea8bbb540f69cc70ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":20,
                  "y":268},
                "size":{
                  "width":200,
                  "height":200},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_0/u28.png"}},
{
          "id":"b5c36c44bb64451c9f83c1af549cc0cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":260,
              "y":268},
            "size":{
              "width":113,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb67b399f54f4125a31fd2aff78af7fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":260,
                  "y":268},
                "size":{
                  "width":113,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6519a5d923c3498d94218ca24dfae11a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Light', '微软雅黑'",
            "fontSize":"24px",
            "fontWeight":"290",
            "location":{
              "x":260,
              "y":328},
            "size":{
              "width":310,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"116f1d275b734843aa235e3633ce1b86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Light', '微软雅黑'",
                "fontSize":"24px",
                "fontWeight":"290",
                "location":{
                  "x":260,
                  "y":328},
                "size":{
                  "width":310,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"334dbb87f74544d5af1da7e662121ff2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":260,
              "y":435},
            "size":{
              "width":103,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07ae9e179b4e4d21bf2fc79b8ed1b77c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":260,
                  "y":435},
                "size":{
                  "width":103,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9839683eeba445ab836e7b4242f4f87e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":603,
              "y":268},
            "size":{
              "width":97,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12f761565fca474488082456f298474c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":603,
                  "y":268},
                "size":{
                  "width":97,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76831c89999949d88f0010127bc185a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":650,
              "y":418},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bce599e34f66437ea10b2c29befdd2fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":650,
                  "y":418},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘列表条目/u12.png"}},
{
          "id":"25ac7921a75e4154bdb0509c30ca932c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":646,
              "y":311},
            "size":{
              "width":54,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2cc85b876004c0c83f837fb9bb24569",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":646,
                  "y":311},
                "size":{
                  "width":54,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f87f41b079fc4e19934968c5e2273bd2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":482},
            "size":{
              "width":460,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页_-_0/u42_line.png"}},
{
          "id":"2d054aec53254a92964b65f60483c94a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":488},
            "size":{
              "width":720,
              "height":240},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d950a4ed1ff4a588d2eace7d9bf7b13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":488},
                "size":{
                  "width":720,
                  "height":240},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_0/u26.png"}},
{
          "id":"f34ecb46b9484031b028c9b64acceaba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":20,
              "y":508},
            "size":{
              "width":200,
              "height":200},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c601a1e637cb46459c1a09de8a745c06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":20,
                  "y":508},
                "size":{
                  "width":200,
                  "height":200},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_0/u28.png"}},
{
          "id":"4d534132e6f54f56a508b1a80789eb72",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":260,
              "y":508},
            "size":{
              "width":113,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10361712641d4162861839cccaa89ec2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":260,
                  "y":508},
                "size":{
                  "width":113,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d06bf6b7f4104588bb2015629f299434",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Light', '微软雅黑'",
            "fontSize":"24px",
            "fontWeight":"290",
            "location":{
              "x":260,
              "y":568},
            "size":{
              "width":310,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9211bffc31ff43ccae4022a22c208b5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Light', '微软雅黑'",
                "fontSize":"24px",
                "fontWeight":"290",
                "location":{
                  "x":260,
                  "y":568},
                "size":{
                  "width":310,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56c6ec3276074bfc96006cf76aa7dab5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":260,
              "y":675},
            "size":{
              "width":103,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebdde65654c241828b6b2c747e4b579d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":260,
                  "y":675},
                "size":{
                  "width":103,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c61388efa854430184b5d4dcce1613ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":603,
              "y":508},
            "size":{
              "width":97,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afa64a538794493eaa874be625177023",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":603,
                  "y":508},
                "size":{
                  "width":97,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f308bf8ce4b5419d8a387c1710ca7b27",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":650,
              "y":658},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be846e350cac4ade8a3d0cb962c8dab7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":650,
                  "y":658},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_0/u55.png"}},
{
          "id":"b163f90e81d440c598f42a26c24ec644",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":646,
              "y":551},
            "size":{
              "width":54,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b29ca32fbd1442c8bf03d2f45890449a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":646,
                  "y":551},
                "size":{
                  "width":54,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1848e07c8bd248debae9e9f6408af461",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":722},
            "size":{
              "width":460,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页_-_0/u42_line.png"}},
{
          "id":"4ccd08f0681b468e8583927a36253376",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":728},
            "size":{
              "width":720,
              "height":240},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77d6b02ed2044470b4d2c0fe7faa7a38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":728},
                "size":{
                  "width":720,
                  "height":240},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_0/u26.png"}},
{
          "id":"41c53c05d92c42d495fa90e77f5e6bbf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":20,
              "y":748},
            "size":{
              "width":200,
              "height":200},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"942e63357b6d4baf8c2fd3d08e03523b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":20,
                  "y":748},
                "size":{
                  "width":200,
                  "height":200},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_0/u28.png"}},
{
          "id":"d2a73263fc594d209cd5676ad2fd558c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":260,
              "y":748},
            "size":{
              "width":113,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e20af8e4c6724a21bc295ba05dd81b23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":260,
                  "y":748},
                "size":{
                  "width":113,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a829f447a9314e379cab797da6eed341",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Light', '微软雅黑'",
            "fontSize":"24px",
            "fontWeight":"290",
            "location":{
              "x":260,
              "y":808},
            "size":{
              "width":310,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ba886ccb1e2418fa024a42fe1ff3e44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Light', '微软雅黑'",
                "fontSize":"24px",
                "fontWeight":"290",
                "location":{
                  "x":260,
                  "y":808},
                "size":{
                  "width":310,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"04fede3acf2f40deb2ea009b2dba2c8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":260,
              "y":915},
            "size":{
              "width":103,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"533cdd7247ce4010a6e4da66a4642ac3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":260,
                  "y":915},
                "size":{
                  "width":103,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e48f39a61944863a2b903bc00aaa38f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":603,
              "y":748},
            "size":{
              "width":97,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19b2d7cf20d14cdaa89d4d1ecc1b7083",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":603,
                  "y":748},
                "size":{
                  "width":97,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86c95ca8d4a847eba92a3ba32ce675e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":650,
              "y":898},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"362b6bed2029406a902bbfc2102e2137",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":650,
                  "y":898},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘列表条目/u12.png"}},
{
          "id":"d2ea4ea2765a4aaba621c959fed463ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":646,
              "y":791},
            "size":{
              "width":54,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d7781bf71a24aaca10f9fa6c3ee88a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":646,
                  "y":791},
                "size":{
                  "width":54,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a770dae42344742849988b0abad1cc6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":962},
            "size":{
              "width":460,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页_-_0/u42_line.png"}},
{
          "id":"0d2f7b5564fb4d8ab653f9623533fffa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":968},
            "size":{
              "width":720,
              "height":240},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0eddc8c5e3c4054b8d5c5b3864b0931",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":968},
                "size":{
                  "width":720,
                  "height":240},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_0/u26.png"}},
{
          "id":"ac490b14620d428d89e2e7b217297225",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":20,
              "y":988},
            "size":{
              "width":200,
              "height":200},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3d19a97d41e4897bf376d105d52b3ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":20,
                  "y":988},
                "size":{
                  "width":200,
                  "height":200},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_0/u28.png"}},
{
          "id":"980899b49f2942e38c45feaf6835da33",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":260,
              "y":988},
            "size":{
              "width":113,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67139dec440a4b73a2c14b4a754faa01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":260,
                  "y":988},
                "size":{
                  "width":113,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a786b85d2664ec99e047de4dac59208",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Light', '微软雅黑'",
            "fontSize":"24px",
            "fontWeight":"290",
            "location":{
              "x":260,
              "y":1048},
            "size":{
              "width":310,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cd02d4ae04d4966b49b455ba7213761",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Light', '微软雅黑'",
                "fontSize":"24px",
                "fontWeight":"290",
                "location":{
                  "x":260,
                  "y":1048},
                "size":{
                  "width":310,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cce84cafb39a45e8ac266e178750d42b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":260,
              "y":1155},
            "size":{
              "width":103,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8380f3f1e073478e8dd9c4830f98fb75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":260,
                  "y":1155},
                "size":{
                  "width":103,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6aed49452ad42a2ba9993549932ef86",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":603,
              "y":988},
            "size":{
              "width":97,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f21818e4c1084d958a4e4376d2321267",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":603,
                  "y":988},
                "size":{
                  "width":97,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b811c65a67d477eba3463f85a085ad4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":650,
              "y":1138},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3efbdf814acc4819beaa99374940e527",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":650,
                  "y":1138},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘列表条目/u12.png"}},
{
          "id":"31641d1547864939a74592e2f6a1b65c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":646,
              "y":1031},
            "size":{
              "width":54,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff93dee5a4184ca38ef689b56abd6baf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":646,
                  "y":1031},
                "size":{
                  "width":54,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"443699dcd6b744369d72fa74a63eb302",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":1202},
            "size":{
              "width":460,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页_-_0/u42_line.png"}},
{
          "id":"c94f121a1daf4bd8abe2a181f89f0315",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":0,
              "y":1182},
            "size":{
              "width":720,
              "height":98},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea2565c3012243819b7a32f7eb3fbf8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":0,
                  "y":1182},
                "size":{
                  "width":720,
                  "height":98},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u2.png"}},
{
          "id":"00dfa9f40e194bcebf277b4223ef1f00",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":137,
              "y":1206},
            "size":{
              "width":42,
              "height":50},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA2A2A2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21faff7c30db469aa47a43fb6a97e372",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":137,
                  "y":1206},
                "size":{
                  "width":42,
                  "height":50},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA2A2A2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u4.png"}},
{
          "id":"159afc21c1f2441ba384460795b4c65a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":335,
              "y":1206},
            "size":{
              "width":50,
              "height":50},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA2A2A2},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d96be78a8eb4979a4bb7d0b09fd1ef4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":335,
                  "y":1206},
                "size":{
                  "width":50,
                  "height":50},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA2A2A2},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u6.png"}},
{
          "id":"7402c99d338942a9a9849eafc0925b31",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":541,
              "y":1209},
            "size":{
              "width":44,
              "height":44},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA2A2A2},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3f3d5f278464d42b9ce40454707c7cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":541,
                  "y":1209},
                "size":{
                  "width":44,
                  "height":44},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA2A2A2},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u8.png"}},
{
          "id":"eff1ac2fc6a44dbe9f88ab9ead7dae3a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":645,
              "y":73},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f345a15366254121bfa3e7dc3d0a9173",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":645,
                  "y":73},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_0/u102.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "11bd4ca700a5472babf0f942e0bff57c":{
      "scriptId":"u0"},
    "102e734053f24774ba06ba697d682e20":{
      "scriptId":"u1"},
    "10ba221f9c764491aee9766eda78e7dd":{
      "scriptId":"u2"},
    "b240c1403c8e4d809c553054311550fb":{
      "scriptId":"u3"},
    "1805d694bae54a328df0247d0097a044":{
      "scriptId":"u4"},
    "6a209a1e515f4a3e8011876282618cd4":{
      "scriptId":"u5"},
    "da7620abe4954f3a9100cfff871b8d9d":{
      "scriptId":"u6"},
    "9891ed1612fc4fbaaa39c8acf4099504":{
      "scriptId":"u7"},
    "d97f3d3d8c7f49c99f09adeb8a2da9a1":{
      "scriptId":"u8"},
    "97d72abbe40e4dd6a1489134b7d15c1f":{
      "scriptId":"u9"},
    "a9ce0e93e2194f5d9646a2200205bdfa":{
      "scriptId":"u10"},
    "f7135faaa5514e909a92f21e60e1fc3e":{
      "scriptId":"u11"},
    "8aee7f44637d40cc95e7d6b8acabab1a":{
      "scriptId":"u12"},
    "3bafc3c3802345dca2f2b7616d534906":{
      "scriptId":"u13"},
    "f5a35e23e5414b0cad116d8456d505db":{
      "scriptId":"u14"},
    "fb9bdfa595164df789733792012b45fb":{
      "scriptId":"u15"},
    "841de535cb374b27af91ee5cf4133f92":{
      "scriptId":"u16"},
    "7fe72daabbcb4108be31bcbebae5282f":{
      "scriptId":"u17"},
    "d1ddd6193f8e4929820ef2874713bb0d":{
      "scriptId":"u18"},
    "c6546a0250c841d79ca1f66444d85608":{
      "scriptId":"u19"},
    "5cf431329d36427fb9a3ac2bbcbeea4b":{
      "scriptId":"u20"},
    "12806b4b006c434f9f2057bb6220f5a5":{
      "scriptId":"u21"},
    "d61333bcd24146c8b25d2f68715c6cd3":{
      "scriptId":"u22"},
    "ad32268f71804c20936127a204c5b6dd":{
      "scriptId":"u23"},
    "c6ab52edd3ee42ae93c370e3c01c8a9a":{
      "scriptId":"u24"},
    "81d6b352089e4746b11cfc6cb0135cc7":{
      "scriptId":"u25"},
    "1e4e716952d84a8da28f562214cc0b20":{
      "scriptId":"u26"},
    "5f57fedd4bee4f04a37a17ec67879893":{
      "scriptId":"u27"},
    "a21a26c36a134048a15d809bb3ba69fe":{
      "scriptId":"u28"},
    "793e81a82b9d44ea8bbb540f69cc70ca":{
      "scriptId":"u29"},
    "b5c36c44bb64451c9f83c1af549cc0cd":{
      "scriptId":"u30"},
    "fb67b399f54f4125a31fd2aff78af7fd":{
      "scriptId":"u31"},
    "6519a5d923c3498d94218ca24dfae11a":{
      "scriptId":"u32"},
    "116f1d275b734843aa235e3633ce1b86":{
      "scriptId":"u33"},
    "334dbb87f74544d5af1da7e662121ff2":{
      "scriptId":"u34"},
    "07ae9e179b4e4d21bf2fc79b8ed1b77c":{
      "scriptId":"u35"},
    "9839683eeba445ab836e7b4242f4f87e":{
      "scriptId":"u36"},
    "12f761565fca474488082456f298474c":{
      "scriptId":"u37"},
    "76831c89999949d88f0010127bc185a4":{
      "scriptId":"u38"},
    "bce599e34f66437ea10b2c29befdd2fd":{
      "scriptId":"u39"},
    "25ac7921a75e4154bdb0509c30ca932c":{
      "scriptId":"u40"},
    "a2cc85b876004c0c83f837fb9bb24569":{
      "scriptId":"u41"},
    "f87f41b079fc4e19934968c5e2273bd2":{
      "scriptId":"u42"},
    "2d054aec53254a92964b65f60483c94a":{
      "scriptId":"u43"},
    "8d950a4ed1ff4a588d2eace7d9bf7b13":{
      "scriptId":"u44"},
    "f34ecb46b9484031b028c9b64acceaba":{
      "scriptId":"u45"},
    "c601a1e637cb46459c1a09de8a745c06":{
      "scriptId":"u46"},
    "4d534132e6f54f56a508b1a80789eb72":{
      "scriptId":"u47"},
    "10361712641d4162861839cccaa89ec2":{
      "scriptId":"u48"},
    "d06bf6b7f4104588bb2015629f299434":{
      "scriptId":"u49"},
    "9211bffc31ff43ccae4022a22c208b5a":{
      "scriptId":"u50"},
    "56c6ec3276074bfc96006cf76aa7dab5":{
      "scriptId":"u51"},
    "ebdde65654c241828b6b2c747e4b579d":{
      "scriptId":"u52"},
    "c61388efa854430184b5d4dcce1613ec":{
      "scriptId":"u53"},
    "afa64a538794493eaa874be625177023":{
      "scriptId":"u54"},
    "f308bf8ce4b5419d8a387c1710ca7b27":{
      "scriptId":"u55"},
    "be846e350cac4ade8a3d0cb962c8dab7":{
      "scriptId":"u56"},
    "b163f90e81d440c598f42a26c24ec644":{
      "scriptId":"u57"},
    "b29ca32fbd1442c8bf03d2f45890449a":{
      "scriptId":"u58"},
    "1848e07c8bd248debae9e9f6408af461":{
      "scriptId":"u59"},
    "4ccd08f0681b468e8583927a36253376":{
      "scriptId":"u60"},
    "77d6b02ed2044470b4d2c0fe7faa7a38":{
      "scriptId":"u61"},
    "41c53c05d92c42d495fa90e77f5e6bbf":{
      "scriptId":"u62"},
    "942e63357b6d4baf8c2fd3d08e03523b":{
      "scriptId":"u63"},
    "d2a73263fc594d209cd5676ad2fd558c":{
      "scriptId":"u64"},
    "e20af8e4c6724a21bc295ba05dd81b23":{
      "scriptId":"u65"},
    "a829f447a9314e379cab797da6eed341":{
      "scriptId":"u66"},
    "7ba886ccb1e2418fa024a42fe1ff3e44":{
      "scriptId":"u67"},
    "04fede3acf2f40deb2ea009b2dba2c8e":{
      "scriptId":"u68"},
    "533cdd7247ce4010a6e4da66a4642ac3":{
      "scriptId":"u69"},
    "3e48f39a61944863a2b903bc00aaa38f":{
      "scriptId":"u70"},
    "19b2d7cf20d14cdaa89d4d1ecc1b7083":{
      "scriptId":"u71"},
    "86c95ca8d4a847eba92a3ba32ce675e5":{
      "scriptId":"u72"},
    "362b6bed2029406a902bbfc2102e2137":{
      "scriptId":"u73"},
    "d2ea4ea2765a4aaba621c959fed463ba":{
      "scriptId":"u74"},
    "2d7781bf71a24aaca10f9fa6c3ee88a0":{
      "scriptId":"u75"},
    "8a770dae42344742849988b0abad1cc6":{
      "scriptId":"u76"},
    "0d2f7b5564fb4d8ab653f9623533fffa":{
      "scriptId":"u77"},
    "c0eddc8c5e3c4054b8d5c5b3864b0931":{
      "scriptId":"u78"},
    "ac490b14620d428d89e2e7b217297225":{
      "scriptId":"u79"},
    "c3d19a97d41e4897bf376d105d52b3ba":{
      "scriptId":"u80"},
    "980899b49f2942e38c45feaf6835da33":{
      "scriptId":"u81"},
    "67139dec440a4b73a2c14b4a754faa01":{
      "scriptId":"u82"},
    "6a786b85d2664ec99e047de4dac59208":{
      "scriptId":"u83"},
    "4cd02d4ae04d4966b49b455ba7213761":{
      "scriptId":"u84"},
    "cce84cafb39a45e8ac266e178750d42b":{
      "scriptId":"u85"},
    "8380f3f1e073478e8dd9c4830f98fb75":{
      "scriptId":"u86"},
    "a6aed49452ad42a2ba9993549932ef86":{
      "scriptId":"u87"},
    "f21818e4c1084d958a4e4376d2321267":{
      "scriptId":"u88"},
    "4b811c65a67d477eba3463f85a085ad4":{
      "scriptId":"u89"},
    "3efbdf814acc4819beaa99374940e527":{
      "scriptId":"u90"},
    "31641d1547864939a74592e2f6a1b65c":{
      "scriptId":"u91"},
    "ff93dee5a4184ca38ef689b56abd6baf":{
      "scriptId":"u92"},
    "443699dcd6b744369d72fa74a63eb302":{
      "scriptId":"u93"},
    "c94f121a1daf4bd8abe2a181f89f0315":{
      "scriptId":"u94"},
    "ea2565c3012243819b7a32f7eb3fbf8c":{
      "scriptId":"u95"},
    "00dfa9f40e194bcebf277b4223ef1f00":{
      "scriptId":"u96"},
    "21faff7c30db469aa47a43fb6a97e372":{
      "scriptId":"u97"},
    "159afc21c1f2441ba384460795b4c65a":{
      "scriptId":"u98"},
    "6d96be78a8eb4979a4bb7d0b09fd1ef4":{
      "scriptId":"u99"},
    "7402c99d338942a9a9849eafc0925b31":{
      "scriptId":"u100"},
    "c3f3d5f278464d42b9ce40454707c7cf":{
      "scriptId":"u101"},
    "eff1ac2fc6a44dbe9f88ab9ead7dae3a":{
      "scriptId":"u102"},
    "f345a15366254121bfa3e7dc3d0a9173":{
      "scriptId":"u103"}}});