$axure.loadCurrentPage({
  "url":"主页_-_1.html",
  "generationDate":new Date(1414911759004.63),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"37a4370a82fb44be93e5b27bffce2c65",
    "type":"Axure:Page",
    "name":"主页 - 1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"34ff5bb1b03a4deab57531331a13ce99",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFCFCFC},
            "location":{
              "x":0,
              "y":-5},
            "size":{
              "width":720,
              "height":1280},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a07942863bb345e4ae6295a404a21bb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFCFCFC},
                "location":{
                  "x":0,
                  "y":-5},
                "size":{
                  "width":720,
                  "height":1280},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u0.png"}},
{
          "id":"a70e73c3716e48e091d6f1fd64ec992c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "size":{
              "width":720,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"039f76d016b44207b74a57c9770a7b44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "size":{
                  "width":720,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录界面/u10.png"}},
{
          "id":"a6c6c96ffbb3405fa10819c6a4b44ebc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Roboto Thin', 'Roboto'",
            "fontWeight":"250",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF8F8FA,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":642,
              "y":10},
            "size":{
              "width":51,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7e5c2d7038546238a823d7dc2438cd7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Thin', 'Roboto'",
                "fontWeight":"250",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF8F8FA,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":642,
                  "y":10},
                "size":{
                  "width":51,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u12.png"}},
{
          "id":"28ac43c3906c4178aea5f8b4129f6b49",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":604,
              "y":23},
            "size":{
              "width":18,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF8F8FA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69a4fd8049e84763a0d15b4e0c302756",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":604,
                  "y":23},
                "size":{
                  "width":18,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF8F8FA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u14.png"}},
{
          "id":"9822acbad764447f9c1d4db22544b53e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":604,
              "y":11},
            "size":{
              "width":18,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC6C6C6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"159a7ae28fdc4af2b31bf5a9f71dd2ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":604,
                  "y":11},
                "size":{
                  "width":18,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC6C6C6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u16.png"}},
{
          "id":"fc74e7cc080b4e56866e0b6859df6807",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":608,
              "y":9},
            "size":{
              "width":8,
              "height":2},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC6C6C6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"635571b88e2f454b9e6ff90ad3df1eee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":608,
                  "y":9},
                "size":{
                  "width":8,
                  "height":2},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC6C6C6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u18.png"}},
{
          "id":"1bc841bf4ed2454591f9c501d3dcd77f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":0,
              "y":48},
            "size":{
              "width":720,
              "height":100},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edc10123a66047a18a3f9821934535ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":0,
                  "y":48},
                "size":{
                  "width":720,
                  "height":100},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航栏/u0.png"}},
{
          "id":"5092295a82144f43b724c48aca4b9369",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":97,
              "y":79},
            "size":{
              "width":145,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5dc2c24553144ac888bb20b828d297f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":97,
                  "y":79},
                "size":{
                  "width":145,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_0/u14.png"}},
{
          "id":"ea4c21af11b241b88468b01361f60a79",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":75},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fcafc914b254651aa12ce4e64f783f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":75},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_0/u16.png"}},
{
          "id":"3ce43a31ab1d49be843cd0d52f92b21b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":575,
              "y":73},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abcea9298d8b44d79a5365083a81caa4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":575,
                  "y":73},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_0/u18.png"}},
{
          "id":"63f56ff05f284c1d8093c05239ea8c7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":0,
              "y":148},
            "size":{
              "width":360,
              "height":100},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fd5883e12f846a8ac473540817a08cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":0,
                  "y":148},
                "size":{
                  "width":360,
                  "height":100},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_0/u20.png"}},
{
          "id":"d84da392cd0046b2be789e6576ed3dc5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":360,
              "y":148},
            "size":{
              "width":360,
              "height":100},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b78cb6dfcbd442f28a93d9d61b1c75eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":360,
                  "y":148},
                "size":{
                  "width":360,
                  "height":100},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_0/u20.png"}},
{
          "id":"09576528b22c4ec4bfd4c44076270c26",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF00},
            "location":{
              "x":0,
              "y":238},
            "size":{
              "width":360,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"168c814fa8b84fd586d64964385bf72d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF00},
                "location":{
                  "x":0,
                  "y":238},
                "size":{
                  "width":360,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_0/u24.png"}},
{
          "id":"c63b5184fd8d4fefb954801d63bf6161",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":0,
              "y":1182},
            "size":{
              "width":720,
              "height":98},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c1a5114f95045d2903737c690aad57d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":0,
                  "y":1182},
                "size":{
                  "width":720,
                  "height":98},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u2.png"}},
{
          "id":"8e1428c479a44cbfb14c47fc68fd48d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":137,
              "y":1206},
            "size":{
              "width":42,
              "height":50},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA2A2A2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9de259ccd904db9a3578bd5d962f7c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":137,
                  "y":1206},
                "size":{
                  "width":42,
                  "height":50},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA2A2A2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u4.png"}},
{
          "id":"786bfa9a82664b46975b0cc478f74573",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":335,
              "y":1206},
            "size":{
              "width":50,
              "height":50},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA2A2A2},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9ee47dcaf6b412a9745107705266061",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":335,
                  "y":1206},
                "size":{
                  "width":50,
                  "height":50},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA2A2A2},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u6.png"}},
{
          "id":"e75828a0ee7a497ea66d336378876673",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":541,
              "y":1209},
            "size":{
              "width":44,
              "height":44},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA2A2A2},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df489a7eeb3b4e85874065a934830cc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":541,
                  "y":1209},
                "size":{
                  "width":44,
                  "height":44},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA2A2A2},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u8.png"}},
{
          "id":"800c513bcacc43a59d145a7416c6c989",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":248},
            "size":{
              "width":720,
              "height":186},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6de4f153a774e99b7d2bc950c234efa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":248},
                "size":{
                  "width":720,
                  "height":186},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘列表条目/u17.png"}},
{
          "id":"d38f373b153d414686dc91dce9a4dde0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":20,
              "y":268},
            "size":{
              "width":150,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"898e44f2d1ec4d91bb45f082bde2926b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":20,
                  "y":268},
                "size":{
                  "width":150,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_1/u36.png"}},
{
          "id":"f6ce1d2f211e422bb70a244c189a0bd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":200,
              "y":268},
            "size":{
              "width":113,
              "height":33},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd4bd01d6ce34b96a3e8a0616fffb3aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":200,
                  "y":268},
                "size":{
                  "width":113,
                  "height":33},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"55fce1b49e2e493d8f89529cf313c2ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Light', '微软雅黑'",
            "fontSize":"24px",
            "fontWeight":"290",
            "location":{
              "x":200,
              "y":311},
            "size":{
              "width":380,
              "height":62},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41d010583a184357a6529f7d517c91fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Light', '微软雅黑'",
                "fontSize":"24px",
                "fontWeight":"290",
                "location":{
                  "x":200,
                  "y":311},
                "size":{
                  "width":380,
                  "height":62},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dae9c70350b7437c927d90b942b20afe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":200,
              "y":383},
            "size":{
              "width":103,
              "height":24},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23d9291a7f2147768bdf07df9bda1d6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":383},
                "size":{
                  "width":103,
                  "height":24},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"42fa743d2bc54f5a8b43f31b7717ffd8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":603,
              "y":268},
            "size":{
              "width":97,
              "height":33},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec5cc4e3eede412db2b680a00cfd688d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":603,
                  "y":268},
                "size":{
                  "width":97,
                  "height":33},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"09a0a7a6717f470ab9aa3fb977625917",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":640,
              "y":357},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6eb27d542fd54f2ba6313f10f2ec49a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":640,
                  "y":357},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘列表条目/u29.png"}},
{
          "id":"e0e61008627445dfad4773ed01b9c885",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":646,
              "y":307},
            "size":{
              "width":54,
              "height":24},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c211d941242e4e05ae500f59ac6ddca3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":646,
                  "y":307},
                "size":{
                  "width":54,
                  "height":24},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"975b0d84ba5b4eefb767b3bf43bcd4be",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":427},
            "size":{
              "width":520,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/招聘列表条目/u33_line.png"}},
{
          "id":"733b23f6dfb546229a10d3587a6fc99d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":434},
            "size":{
              "width":720,
              "height":186},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9bcd848e712944a49ebd24fbb5fe3d63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":434},
                "size":{
                  "width":720,
                  "height":186},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘列表条目/u17.png"}},
{
          "id":"fcc7df461274442fb6a9eb8d2670b264",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":20,
              "y":454},
            "size":{
              "width":150,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a564230da2854bc5bf3f7113f6ac000d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":20,
                  "y":454},
                "size":{
                  "width":150,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_1/u36.png"}},
{
          "id":"973b9bb37d034f389657dbe9a09252cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":200,
              "y":454},
            "size":{
              "width":113,
              "height":33},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dac29ac40c8d4b708701f764091c828d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":200,
                  "y":454},
                "size":{
                  "width":113,
                  "height":33},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c9aed2f8937f495b89ddc7ef9a1da605",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Light', '微软雅黑'",
            "fontSize":"24px",
            "fontWeight":"290",
            "location":{
              "x":200,
              "y":497},
            "size":{
              "width":380,
              "height":62},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"770416bb2ebd4108b3a8f50ac6272f1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Light', '微软雅黑'",
                "fontSize":"24px",
                "fontWeight":"290",
                "location":{
                  "x":200,
                  "y":497},
                "size":{
                  "width":380,
                  "height":62},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"75a782ddccb0461397749263f0a3f748",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":200,
              "y":569},
            "size":{
              "width":103,
              "height":24},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87524267c4ee45b399eba12e3dd27239",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":569},
                "size":{
                  "width":103,
                  "height":24},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"62415c7948d24983840890e27548ac37",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":603,
              "y":454},
            "size":{
              "width":85,
              "height":33},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"148c31ba106e48f281559fb5a4e87e03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":603,
                  "y":454},
                "size":{
                  "width":85,
                  "height":33},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7bc1f7ad8eea4e8ea8b42674c4a57dea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":640,
              "y":543},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91a9b3e2e1f7405f9de01823d7f90c71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":640,
                  "y":543},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_1/u63.png"}},
{
          "id":"ea12c9d7ca3e45d3b15abe0648ed611a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":646,
              "y":493},
            "size":{
              "width":52,
              "height":24},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"843e3bdde28447efba7789f481ea4e93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":646,
                  "y":493},
                "size":{
                  "width":52,
                  "height":24},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e48fc24d1834beb888443cf89c39d43",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":613},
            "size":{
              "width":520,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/招聘列表条目/u33_line.png"}},
{
          "id":"855a84ad6bc2492eaddeb02f4da57bb8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":620},
            "size":{
              "width":720,
              "height":186},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c5c9b1d6b4046b4924e4a48896a63f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":620},
                "size":{
                  "width":720,
                  "height":186},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘列表条目/u17.png"}},
{
          "id":"2671466c76624b93bb9b4e37e4ae2e4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":20,
              "y":640},
            "size":{
              "width":150,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d27509541ef4b71b6cb6962224f4f0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":20,
                  "y":640},
                "size":{
                  "width":150,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_1/u36.png"}},
{
          "id":"85d35fbfe7e74e2c92e0b341fe827acf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":200,
              "y":640},
            "size":{
              "width":113,
              "height":33},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52dc8f58fbd04aacaf0197a7606ecfa5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":200,
                  "y":640},
                "size":{
                  "width":113,
                  "height":33},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e7e6319807fa451caa2e17ade8de4002",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Light', '微软雅黑'",
            "fontSize":"24px",
            "fontWeight":"290",
            "location":{
              "x":200,
              "y":683},
            "size":{
              "width":380,
              "height":62},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcb5091f85b54827a47012c925fe093e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Light', '微软雅黑'",
                "fontSize":"24px",
                "fontWeight":"290",
                "location":{
                  "x":200,
                  "y":683},
                "size":{
                  "width":380,
                  "height":62},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8eff1a08157f404a9ad537986f70f314",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":200,
              "y":755},
            "size":{
              "width":103,
              "height":24},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"118a70d1bacd44a18f1e9903aa2ea23e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":755},
                "size":{
                  "width":103,
                  "height":24},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6cbdeec2fde472bb418513f48f79055",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":603,
              "y":640},
            "size":{
              "width":97,
              "height":33},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47c6e6e7b48843bb8557556a22cb1a85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":603,
                  "y":640},
                "size":{
                  "width":97,
                  "height":33},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb239dadf8cd4d79a37d7e628a33a006",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":640,
              "y":729},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e418ae5aa5f94d98b308bab05bdaa567",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":640,
                  "y":729},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘列表条目/u29.png"}},
{
          "id":"bf6ce4c5ae834ec18e9082ba2fda6617",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":646,
              "y":679},
            "size":{
              "width":54,
              "height":24},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c86fce3488249fdaacc0ccf74ad8d3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":646,
                  "y":679},
                "size":{
                  "width":54,
                  "height":24},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf12683808644504a7228ef850a60df2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":799},
            "size":{
              "width":520,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/招聘列表条目/u33_line.png"}},
{
          "id":"fe7d32830d524c36b1f619a56e8b8ad8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":806},
            "size":{
              "width":720,
              "height":186},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dafbea15e36402eb5315e42c075fe89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":806},
                "size":{
                  "width":720,
                  "height":186},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘列表条目/u17.png"}},
{
          "id":"deb263cc0f92487eb8416d56e8c1aa74",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":20,
              "y":826},
            "size":{
              "width":150,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7070c9b57e243f69fe37018a9b6b9f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":20,
                  "y":826},
                "size":{
                  "width":150,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_1/u36.png"}},
{
          "id":"766f6b21748e411d84bed238438869a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":200,
              "y":826},
            "size":{
              "width":113,
              "height":33},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25f8b5aa44c94d8287a3a79f8d75fd48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":200,
                  "y":826},
                "size":{
                  "width":113,
                  "height":33},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0f33e9277fd24cad9a239a7cea4f59a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Light', '微软雅黑'",
            "fontSize":"24px",
            "fontWeight":"290",
            "location":{
              "x":200,
              "y":869},
            "size":{
              "width":380,
              "height":62},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6957b53d19c346379da354c6895c9e11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Light', '微软雅黑'",
                "fontSize":"24px",
                "fontWeight":"290",
                "location":{
                  "x":200,
                  "y":869},
                "size":{
                  "width":380,
                  "height":62},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f4434350ed854ee292030ff2f87ab02f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":200,
              "y":941},
            "size":{
              "width":103,
              "height":24},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"271c2222e9e44a88a7183751a687f291",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":941},
                "size":{
                  "width":103,
                  "height":24},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68dca8a5561e45728aaa8f803289cafa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":603,
              "y":826},
            "size":{
              "width":97,
              "height":33},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d4fc6a3ef6e437e931274baebf854d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":603,
                  "y":826},
                "size":{
                  "width":97,
                  "height":33},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4bf2ebb83ed04a30924610957cce4253",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":640,
              "y":915},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"228d03349bd644f8a16d3564986f3618",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":640,
                  "y":915},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘列表条目/u29.png"}},
{
          "id":"9f15d9c52a084559ba6334e8f9c13719",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":646,
              "y":865},
            "size":{
              "width":54,
              "height":24},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4632b029fc45470ab0d1e408f92e0b20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":646,
                  "y":865},
                "size":{
                  "width":54,
                  "height":24},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ea87281a6794472a1f4ec9e035ca3b3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":985},
            "size":{
              "width":520,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/招聘列表条目/u33_line.png"}},
{
          "id":"0b7d583a2d7f4512b6dc78d5eb9ce4c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":992},
            "size":{
              "width":720,
              "height":186},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b387dd6e3419448cb5db9b92d13cae92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":992},
                "size":{
                  "width":720,
                  "height":186},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘列表条目/u17.png"}},
{
          "id":"d4047328abc14e1b9ebf68df25742ebe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":20,
              "y":1012},
            "size":{
              "width":150,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad27bbd0380d4e27a19d23708530bc38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":20,
                  "y":1012},
                "size":{
                  "width":150,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_1/u36.png"}},
{
          "id":"6f01664721f143e19717623143ef66ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":200,
              "y":1012},
            "size":{
              "width":113,
              "height":33},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c850119631646e6a2183b465d52342b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":200,
                  "y":1012},
                "size":{
                  "width":113,
                  "height":33},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b229a7a360a4b26bce2ec4707a814a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Light', '微软雅黑'",
            "fontSize":"24px",
            "fontWeight":"290",
            "location":{
              "x":200,
              "y":1055},
            "size":{
              "width":380,
              "height":62},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e342b5dd5d14f948868c2811f784e4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Light', '微软雅黑'",
                "fontSize":"24px",
                "fontWeight":"290",
                "location":{
                  "x":200,
                  "y":1055},
                "size":{
                  "width":380,
                  "height":62},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad7ac596d3374ff08f3d8b6aacc61327",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":200,
              "y":1127},
            "size":{
              "width":103,
              "height":24},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e524c81686544b1ebff3542fb9ec5566",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":1127},
                "size":{
                  "width":103,
                  "height":24},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ca63e7f34b54ef0856cf01d4a4a546a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":603,
              "y":1012},
            "size":{
              "width":97,
              "height":33},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c052ab96fd424ea59b8d307834e1ad4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":603,
                  "y":1012},
                "size":{
                  "width":97,
                  "height":33},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"924b6642b9a54b639f64ec97127e6774",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":640,
              "y":1101},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0022494c20134736b202ae1692f2f0a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":640,
                  "y":1101},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/招聘列表条目/u29.png"}},
{
          "id":"d0cac9435d494e6d9d97aba209da2ab6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":646,
              "y":1051},
            "size":{
              "width":54,
              "height":24},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a76655ca4e2a48279df3566224bb755e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":646,
                  "y":1051},
                "size":{
                  "width":54,
                  "height":24},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f86617df2dbe43fea8089cac4da75296",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":1171},
            "size":{
              "width":520,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/招聘列表条目/u33_line.png"}},
{
          "id":"6d2e90f8ef694d7ab9fd999e793009b2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":645,
              "y":73},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cf3575cdeae4d518e0e9a71e20247f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":645,
                  "y":73},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_-_0/u102.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "34ff5bb1b03a4deab57531331a13ce99":{
      "scriptId":"u0"},
    "a07942863bb345e4ae6295a404a21bb8":{
      "scriptId":"u1"},
    "a70e73c3716e48e091d6f1fd64ec992c":{
      "scriptId":"u2"},
    "039f76d016b44207b74a57c9770a7b44":{
      "scriptId":"u3"},
    "a6c6c96ffbb3405fa10819c6a4b44ebc":{
      "scriptId":"u4"},
    "e7e5c2d7038546238a823d7dc2438cd7":{
      "scriptId":"u5"},
    "28ac43c3906c4178aea5f8b4129f6b49":{
      "scriptId":"u6"},
    "69a4fd8049e84763a0d15b4e0c302756":{
      "scriptId":"u7"},
    "9822acbad764447f9c1d4db22544b53e":{
      "scriptId":"u8"},
    "159a7ae28fdc4af2b31bf5a9f71dd2ac":{
      "scriptId":"u9"},
    "fc74e7cc080b4e56866e0b6859df6807":{
      "scriptId":"u10"},
    "635571b88e2f454b9e6ff90ad3df1eee":{
      "scriptId":"u11"},
    "1bc841bf4ed2454591f9c501d3dcd77f":{
      "scriptId":"u12"},
    "edc10123a66047a18a3f9821934535ff":{
      "scriptId":"u13"},
    "5092295a82144f43b724c48aca4b9369":{
      "scriptId":"u14"},
    "d5dc2c24553144ac888bb20b828d297f":{
      "scriptId":"u15"},
    "ea4c21af11b241b88468b01361f60a79":{
      "scriptId":"u16"},
    "4fcafc914b254651aa12ce4e64f783f8":{
      "scriptId":"u17"},
    "3ce43a31ab1d49be843cd0d52f92b21b":{
      "scriptId":"u18"},
    "abcea9298d8b44d79a5365083a81caa4":{
      "scriptId":"u19"},
    "63f56ff05f284c1d8093c05239ea8c7f":{
      "scriptId":"u20"},
    "7fd5883e12f846a8ac473540817a08cf":{
      "scriptId":"u21"},
    "d84da392cd0046b2be789e6576ed3dc5":{
      "scriptId":"u22"},
    "b78cb6dfcbd442f28a93d9d61b1c75eb":{
      "scriptId":"u23"},
    "09576528b22c4ec4bfd4c44076270c26":{
      "scriptId":"u24"},
    "168c814fa8b84fd586d64964385bf72d":{
      "scriptId":"u25"},
    "c63b5184fd8d4fefb954801d63bf6161":{
      "scriptId":"u26"},
    "0c1a5114f95045d2903737c690aad57d":{
      "scriptId":"u27"},
    "8e1428c479a44cbfb14c47fc68fd48d5":{
      "scriptId":"u28"},
    "b9de259ccd904db9a3578bd5d962f7c8":{
      "scriptId":"u29"},
    "786bfa9a82664b46975b0cc478f74573":{
      "scriptId":"u30"},
    "c9ee47dcaf6b412a9745107705266061":{
      "scriptId":"u31"},
    "e75828a0ee7a497ea66d336378876673":{
      "scriptId":"u32"},
    "df489a7eeb3b4e85874065a934830cc8":{
      "scriptId":"u33"},
    "800c513bcacc43a59d145a7416c6c989":{
      "scriptId":"u34"},
    "a6de4f153a774e99b7d2bc950c234efa":{
      "scriptId":"u35"},
    "d38f373b153d414686dc91dce9a4dde0":{
      "scriptId":"u36"},
    "898e44f2d1ec4d91bb45f082bde2926b":{
      "scriptId":"u37"},
    "f6ce1d2f211e422bb70a244c189a0bd1":{
      "scriptId":"u38"},
    "cd4bd01d6ce34b96a3e8a0616fffb3aa":{
      "scriptId":"u39"},
    "55fce1b49e2e493d8f89529cf313c2ef":{
      "scriptId":"u40"},
    "41d010583a184357a6529f7d517c91fc":{
      "scriptId":"u41"},
    "dae9c70350b7437c927d90b942b20afe":{
      "scriptId":"u42"},
    "23d9291a7f2147768bdf07df9bda1d6e":{
      "scriptId":"u43"},
    "42fa743d2bc54f5a8b43f31b7717ffd8":{
      "scriptId":"u44"},
    "ec5cc4e3eede412db2b680a00cfd688d":{
      "scriptId":"u45"},
    "09a0a7a6717f470ab9aa3fb977625917":{
      "scriptId":"u46"},
    "6eb27d542fd54f2ba6313f10f2ec49a1":{
      "scriptId":"u47"},
    "e0e61008627445dfad4773ed01b9c885":{
      "scriptId":"u48"},
    "c211d941242e4e05ae500f59ac6ddca3":{
      "scriptId":"u49"},
    "975b0d84ba5b4eefb767b3bf43bcd4be":{
      "scriptId":"u50"},
    "733b23f6dfb546229a10d3587a6fc99d":{
      "scriptId":"u51"},
    "9bcd848e712944a49ebd24fbb5fe3d63":{
      "scriptId":"u52"},
    "fcc7df461274442fb6a9eb8d2670b264":{
      "scriptId":"u53"},
    "a564230da2854bc5bf3f7113f6ac000d":{
      "scriptId":"u54"},
    "973b9bb37d034f389657dbe9a09252cc":{
      "scriptId":"u55"},
    "dac29ac40c8d4b708701f764091c828d":{
      "scriptId":"u56"},
    "c9aed2f8937f495b89ddc7ef9a1da605":{
      "scriptId":"u57"},
    "770416bb2ebd4108b3a8f50ac6272f1a":{
      "scriptId":"u58"},
    "75a782ddccb0461397749263f0a3f748":{
      "scriptId":"u59"},
    "87524267c4ee45b399eba12e3dd27239":{
      "scriptId":"u60"},
    "62415c7948d24983840890e27548ac37":{
      "scriptId":"u61"},
    "148c31ba106e48f281559fb5a4e87e03":{
      "scriptId":"u62"},
    "7bc1f7ad8eea4e8ea8b42674c4a57dea":{
      "scriptId":"u63"},
    "91a9b3e2e1f7405f9de01823d7f90c71":{
      "scriptId":"u64"},
    "ea12c9d7ca3e45d3b15abe0648ed611a":{
      "scriptId":"u65"},
    "843e3bdde28447efba7789f481ea4e93":{
      "scriptId":"u66"},
    "9e48fc24d1834beb888443cf89c39d43":{
      "scriptId":"u67"},
    "855a84ad6bc2492eaddeb02f4da57bb8":{
      "scriptId":"u68"},
    "7c5c9b1d6b4046b4924e4a48896a63f2":{
      "scriptId":"u69"},
    "2671466c76624b93bb9b4e37e4ae2e4f":{
      "scriptId":"u70"},
    "8d27509541ef4b71b6cb6962224f4f0d":{
      "scriptId":"u71"},
    "85d35fbfe7e74e2c92e0b341fe827acf":{
      "scriptId":"u72"},
    "52dc8f58fbd04aacaf0197a7606ecfa5":{
      "scriptId":"u73"},
    "e7e6319807fa451caa2e17ade8de4002":{
      "scriptId":"u74"},
    "fcb5091f85b54827a47012c925fe093e":{
      "scriptId":"u75"},
    "8eff1a08157f404a9ad537986f70f314":{
      "scriptId":"u76"},
    "118a70d1bacd44a18f1e9903aa2ea23e":{
      "scriptId":"u77"},
    "f6cbdeec2fde472bb418513f48f79055":{
      "scriptId":"u78"},
    "47c6e6e7b48843bb8557556a22cb1a85":{
      "scriptId":"u79"},
    "bb239dadf8cd4d79a37d7e628a33a006":{
      "scriptId":"u80"},
    "e418ae5aa5f94d98b308bab05bdaa567":{
      "scriptId":"u81"},
    "bf6ce4c5ae834ec18e9082ba2fda6617":{
      "scriptId":"u82"},
    "2c86fce3488249fdaacc0ccf74ad8d3c":{
      "scriptId":"u83"},
    "bf12683808644504a7228ef850a60df2":{
      "scriptId":"u84"},
    "fe7d32830d524c36b1f619a56e8b8ad8":{
      "scriptId":"u85"},
    "8dafbea15e36402eb5315e42c075fe89":{
      "scriptId":"u86"},
    "deb263cc0f92487eb8416d56e8c1aa74":{
      "scriptId":"u87"},
    "c7070c9b57e243f69fe37018a9b6b9f0":{
      "scriptId":"u88"},
    "766f6b21748e411d84bed238438869a4":{
      "scriptId":"u89"},
    "25f8b5aa44c94d8287a3a79f8d75fd48":{
      "scriptId":"u90"},
    "0f33e9277fd24cad9a239a7cea4f59a0":{
      "scriptId":"u91"},
    "6957b53d19c346379da354c6895c9e11":{
      "scriptId":"u92"},
    "f4434350ed854ee292030ff2f87ab02f":{
      "scriptId":"u93"},
    "271c2222e9e44a88a7183751a687f291":{
      "scriptId":"u94"},
    "68dca8a5561e45728aaa8f803289cafa":{
      "scriptId":"u95"},
    "7d4fc6a3ef6e437e931274baebf854d1":{
      "scriptId":"u96"},
    "4bf2ebb83ed04a30924610957cce4253":{
      "scriptId":"u97"},
    "228d03349bd644f8a16d3564986f3618":{
      "scriptId":"u98"},
    "9f15d9c52a084559ba6334e8f9c13719":{
      "scriptId":"u99"},
    "4632b029fc45470ab0d1e408f92e0b20":{
      "scriptId":"u100"},
    "8ea87281a6794472a1f4ec9e035ca3b3":{
      "scriptId":"u101"},
    "0b7d583a2d7f4512b6dc78d5eb9ce4c5":{
      "scriptId":"u102"},
    "b387dd6e3419448cb5db9b92d13cae92":{
      "scriptId":"u103"},
    "d4047328abc14e1b9ebf68df25742ebe":{
      "scriptId":"u104"},
    "ad27bbd0380d4e27a19d23708530bc38":{
      "scriptId":"u105"},
    "6f01664721f143e19717623143ef66ce":{
      "scriptId":"u106"},
    "8c850119631646e6a2183b465d52342b":{
      "scriptId":"u107"},
    "7b229a7a360a4b26bce2ec4707a814a5":{
      "scriptId":"u108"},
    "2e342b5dd5d14f948868c2811f784e4d":{
      "scriptId":"u109"},
    "ad7ac596d3374ff08f3d8b6aacc61327":{
      "scriptId":"u110"},
    "e524c81686544b1ebff3542fb9ec5566":{
      "scriptId":"u111"},
    "0ca63e7f34b54ef0856cf01d4a4a546a":{
      "scriptId":"u112"},
    "c052ab96fd424ea59b8d307834e1ad4e":{
      "scriptId":"u113"},
    "924b6642b9a54b639f64ec97127e6774":{
      "scriptId":"u114"},
    "0022494c20134736b202ae1692f2f0a5":{
      "scriptId":"u115"},
    "d0cac9435d494e6d9d97aba209da2ab6":{
      "scriptId":"u116"},
    "a76655ca4e2a48279df3566224bb755e":{
      "scriptId":"u117"},
    "f86617df2dbe43fea8089cac4da75296":{
      "scriptId":"u118"},
    "6d2e90f8ef694d7ab9fd999e793009b2":{
      "scriptId":"u119"},
    "8cf3575cdeae4d518e0e9a71e20247f4":{
      "scriptId":"u120"}}});