$axure.loadCurrentPage({
  "url":"开始页面.html",
  "generationDate":new Date(1414911756684.14),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3e03d95f89b8468e9f13e7918bff7d82",
    "type":"Axure:Page",
    "name":"开始页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Arial",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6c1849c285aa44f19547a8e831643fb2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "fill":{
              "fillType":"solid",
              "color":0xFFFCFCFC},
            "size":{
              "width":720,
              "height":1280},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFCFCFC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cfa60f9a17f484588469d41d25448c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFCFCFC},
                "size":{
                  "width":720,
                  "height":1280},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFCFCFC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u0.png"}},
{
          "id":"e5dc4e6067aa42c08632ed1d2b88363a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":0,
              "y":1182},
            "size":{
              "width":720,
              "height":98},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a87042424754df1b0f0d45663f22b8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":0,
                  "y":1182},
                "size":{
                  "width":720,
                  "height":98},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u2.png"}},
{
          "id":"339835dc9d2f4f9f8b8791606bfa1d1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":137,
              "y":1206},
            "size":{
              "width":42,
              "height":50},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA2A2A2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15af8d48bad7448fb046a3d2fc4fef9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":137,
                  "y":1206},
                "size":{
                  "width":42,
                  "height":50},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA2A2A2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u4.png"}},
{
          "id":"07284eb30024477b97cf93c98a27d954",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":335,
              "y":1206},
            "size":{
              "width":50,
              "height":50},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA2A2A2},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f1ca6ea952d4a8ba3b010e6d37c9e18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":335,
                  "y":1206},
                "size":{
                  "width":50,
                  "height":50},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA2A2A2},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u6.png"}},
{
          "id":"088a6885a1044d1597d16a975b9906cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":541,
              "y":1209},
            "size":{
              "width":44,
              "height":44},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA2A2A2},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6ff1b7cca5a46bbb7b1e1f3cbab73de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":541,
                  "y":1209},
                "size":{
                  "width":44,
                  "height":44},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA2A2A2},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u8.png"}},
{
          "id":"03a951fbfc074cce8be343f0de72fe89",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "size":{
              "width":720,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFB3B3B3}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"388cf44b814349ffb0bf18e4a53b6176",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "size":{
                  "width":720,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFB3B3B3}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u10.png"}},
{
          "id":"2a8431e3eaf64b46aa8312a5f08b491b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF8F8FA,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":642,
              "y":10},
            "size":{
              "width":51,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"218e123cedda406e928f846e1e20c9a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF8F8FA,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":642,
                  "y":10},
                "size":{
                  "width":51,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u12.png"}},
{
          "id":"fe948d38aba44e09919fb7981247fce1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":604,
              "y":23},
            "size":{
              "width":18,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF8F8FA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2393e627ce1e49a2a86e6987729185d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":604,
                  "y":23},
                "size":{
                  "width":18,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF8F8FA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u14.png"}},
{
          "id":"7147e20b05d04b8bb076c3b78020a31a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":604,
              "y":11},
            "size":{
              "width":18,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC6C6C6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c666752eb2843629449f35df14830d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":604,
                  "y":11},
                "size":{
                  "width":18,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC6C6C6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u16.png"}},
{
          "id":"db0cdb9880e943a5ae310563b0f78bc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":608,
              "y":9},
            "size":{
              "width":8,
              "height":2},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC6C6C6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db69ac0578f94c49ba101152c35e5898",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":608,
                  "y":9},
                "size":{
                  "width":8,
                  "height":2},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC6C6C6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u18.png"}},
{
          "id":"7fe7fc522cf34b31bcd340530bb54cc3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"36px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFE6E49,
              "opacity":1},
            "location":{
              "x":320.000030517578,
              "y":486},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"426fe82cc2f348d4a1d69d7c1c85302f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"36px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFE6E49,
                  "opacity":1},
                "location":{
                  "x":320.000030517578,
                  "y":486},
                "size":{
                  "width":23,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d53e73717b9645e28f86494aef89f692",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"72px",
            "fontWeight":"700",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF46E49,
              "opacity":1},
            "location":{
              "x":152,
              "y":376},
            "size":{
              "width":289,
              "height":83},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da55c223e375457aaed1a7e09b0d7518",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"72px",
                "fontWeight":"700",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49,
                  "opacity":1},
                "location":{
                  "x":152,
                  "y":376},
                "size":{
                  "width":289,
                  "height":83},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFE6E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a32089b808ac4bf7838350aaabf9a2bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF46E49,
              "opacity":1},
            "location":{
              "x":258,
              "y":469},
            "size":{
              "width":309,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b8faa47bb7c42929add21c8ffbce51c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF46E49,
                  "opacity":1},
                "location":{
                  "x":258,
                  "y":469},
                "size":{
                  "width":309,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFE6E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "6c1849c285aa44f19547a8e831643fb2":{
      "scriptId":"u0"},
    "0cfa60f9a17f484588469d41d25448c7":{
      "scriptId":"u1"},
    "e5dc4e6067aa42c08632ed1d2b88363a":{
      "scriptId":"u2"},
    "0a87042424754df1b0f0d45663f22b8d":{
      "scriptId":"u3"},
    "339835dc9d2f4f9f8b8791606bfa1d1f":{
      "scriptId":"u4"},
    "15af8d48bad7448fb046a3d2fc4fef9d":{
      "scriptId":"u5"},
    "07284eb30024477b97cf93c98a27d954":{
      "scriptId":"u6"},
    "1f1ca6ea952d4a8ba3b010e6d37c9e18":{
      "scriptId":"u7"},
    "088a6885a1044d1597d16a975b9906cc":{
      "scriptId":"u8"},
    "c6ff1b7cca5a46bbb7b1e1f3cbab73de":{
      "scriptId":"u9"},
    "03a951fbfc074cce8be343f0de72fe89":{
      "scriptId":"u10"},
    "388cf44b814349ffb0bf18e4a53b6176":{
      "scriptId":"u11"},
    "2a8431e3eaf64b46aa8312a5f08b491b":{
      "scriptId":"u12"},
    "218e123cedda406e928f846e1e20c9a0":{
      "scriptId":"u13"},
    "fe948d38aba44e09919fb7981247fce1":{
      "scriptId":"u14"},
    "2393e627ce1e49a2a86e6987729185d9":{
      "scriptId":"u15"},
    "7147e20b05d04b8bb076c3b78020a31a":{
      "scriptId":"u16"},
    "8c666752eb2843629449f35df14830d6":{
      "scriptId":"u17"},
    "db0cdb9880e943a5ae310563b0f78bc8":{
      "scriptId":"u18"},
    "db69ac0578f94c49ba101152c35e5898":{
      "scriptId":"u19"},
    "7fe7fc522cf34b31bcd340530bb54cc3":{
      "scriptId":"u20"},
    "426fe82cc2f348d4a1d69d7c1c85302f":{
      "scriptId":"u21"},
    "d53e73717b9645e28f86494aef89f692":{
      "scriptId":"u22"},
    "da55c223e375457aaed1a7e09b0d7518":{
      "scriptId":"u23"},
    "a32089b808ac4bf7838350aaabf9a2bf":{
      "scriptId":"u24"},
    "6b8faa47bb7c42929add21c8ffbce51c":{
      "scriptId":"u25"}}});