$axure.loadCurrentPage({
  "url":"忘记密码.html",
  "generationDate":new Date(1414911758206.17),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5c1977d2909d46a09deedb6c90ffae03",
    "type":"Axure:Page",
    "name":"忘记密码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8fe874335b4448e1ba14374e21e47277",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFCFCFC},
            "size":{
              "width":720,
              "height":1280},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFCFCFC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c8f80b85e6f49fea01f09ed7d8440ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFCFCFC},
                "size":{
                  "width":720,
                  "height":1280},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFCFCFC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u0.png"}},
{
          "id":"9baec5c8e02a4a0fa1898ac58380b4a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":0,
              "y":1182},
            "size":{
              "width":720,
              "height":98},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a15277bc384a41e4bec0028ed1f8b495",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":0,
                  "y":1182},
                "size":{
                  "width":720,
                  "height":98},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u2.png"}},
{
          "id":"68512d91e1f449459977fef7a8bafdda",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":137,
              "y":1206},
            "size":{
              "width":42,
              "height":50},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA2A2A2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26a5a73152ca4dbca89b2b5756003074",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":137,
                  "y":1206},
                "size":{
                  "width":42,
                  "height":50},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA2A2A2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u4.png"}},
{
          "id":"a746150b4213452384fea6d28359bc27",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":335,
              "y":1206},
            "size":{
              "width":50,
              "height":50},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA2A2A2},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97c6ba8d681544a19e7fe83f7d77c682",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":335,
                  "y":1206},
                "size":{
                  "width":50,
                  "height":50},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA2A2A2},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u6.png"}},
{
          "id":"e95e67458c984f99bd2f3e1727f423ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":541,
              "y":1209},
            "size":{
              "width":44,
              "height":44},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA2A2A2},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01232e25300147debbd82e148b94124c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":541,
                  "y":1209},
                "size":{
                  "width":44,
                  "height":44},
                "borderWidth":"4",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA2A2A2},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u8.png"}},
{
          "id":"c0d0b3a46d5645ab92b03f60032ac7f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000}]},
            "size":{
              "width":720,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFB3B3B3}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9646d1c148d34cdd89ba1c1d30dd5380",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000}]},
                "size":{
                  "width":720,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFB3B3B3}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u10.png"}},
{
          "id":"7f2a190367bd4ca6ac9f144d68960b7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Roboto Thin', 'Roboto'",
            "fontWeight":"250",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF8F8FA,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000}]},
            "location":{
              "x":642,
              "y":10},
            "size":{
              "width":51,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"875ec0b5dac1438986f284d95477f747",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Thin', 'Roboto'",
                "fontWeight":"250",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF8F8FA,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000}]},
                "location":{
                  "x":642,
                  "y":10},
                "size":{
                  "width":51,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u12.png"}},
{
          "id":"a98874ee8c1344469690333207db33ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000}]},
            "location":{
              "x":604,
              "y":23},
            "size":{
              "width":18,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c658a45888354917b493112f2cf5ef3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000}]},
                "location":{
                  "x":604,
                  "y":23},
                "size":{
                  "width":18,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/忘记密码/u14.png"}},
{
          "id":"3774bf2f76ef4b87a67e240dd66e83cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000}]},
            "location":{
              "x":604,
              "y":11},
            "size":{
              "width":18,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3363d544e75f420d8b77baaabc918eff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000}]},
                "location":{
                  "x":604,
                  "y":11},
                "size":{
                  "width":18,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/忘记密码/u14.png"}},
{
          "id":"0b5c145cd4fc455785f7367bd9fd3967",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000}]},
            "location":{
              "x":608,
              "y":9},
            "size":{
              "width":8,
              "height":2},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC6C6C6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bd1d048cd454feeb02bea22baba0564",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000}]},
                "location":{
                  "x":608,
                  "y":9},
                "size":{
                  "width":8,
                  "height":2},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC6C6C6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始页面/u18.png"}},
{
          "id":"21cdb275dcc641c09ce9dba524db8274",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF46E49},
            "location":{
              "x":0,
              "y":48},
            "size":{
              "width":720,
              "height":100},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b466d1f51ed142c7b5c395f52fd17075",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF46E49},
                "location":{
                  "x":0,
                  "y":48},
                "size":{
                  "width":720,
                  "height":100},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFE6E49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航栏/u0.png"}},
{
          "id":"cd5f07227531459c930c0d3ad8123b5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":100,
              "y":77},
            "size":{
              "width":145,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16efb181c24645eab1471c7c78c7aa87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":100,
                  "y":77},
                "size":{
                  "width":145,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fef3c4c8172c41e48020a8e95f7d52db",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":75},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fae53d88c1b94ba4ba45e4f977ece253",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":75},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/忘记密码/u24.png"}},
{
          "id":"94529e453179486dad8badb2329afc82",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":645,
              "y":73},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8053c8bb2084ac892550ae0d643bdf4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":645,
                  "y":73},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/忘记密码/u26.png"}},
{
          "id":"a0e364d2f75442f583be2c7d566900b5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":239},
            "size":{
              "width":624,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u0_line.png"}},
{
          "id":"a6179b13646f460f8c416b8ffd1edb47",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":237},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u1_line.png"}},
{
          "id":"9d6291ca4adb4bf8839f2a06bc048d2e",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":666,
              "y":237},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u1_line.png"}},
{
          "id":"e6a73859b9834306a4edf805914b6624",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":64,
              "y":203},
            "size":{
              "width":85,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fc5b4b0325d4ea9b379da1b288d7455",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":64,
                  "y":203},
                "size":{
                  "width":85,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de1f0cac9ab04465a9e31ec89c98e068",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":330},
            "size":{
              "width":624,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u3_line.png"}},
{
          "id":"c27f246b5c6342938ebf5a2a5775f50f",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":328},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u4_line.png"}},
{
          "id":"0c3854de3f774f43adb7ed5a68463e92",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":666,
              "y":328},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u4_line.png"}},
{
          "id":"db2487428a434dd188b6a03cc844cfa7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":64,
              "y":294},
            "size":{
              "width":141,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFEAEAEA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15ada4ef4e8f423eb206a1f523763bbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":64,
                  "y":294},
                "size":{
                  "width":141,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFEAEAEA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28e34d836e894efb8d85d5a04aa56c95",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":464,
              "y":237},
            "size":{
              "width":10,
              "height":8},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFE6E49}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/文本输入/u1_line.png"}},
{
          "id":"61d8a895ba4349e49160300ae1f8f0f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFE6E49,
              "opacity":1},
            "location":{
              "x":503,
              "y":203},
            "size":{
              "width":141,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a672d1f84104b96beb345aea52202de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFE6E49,
                  "opacity":1},
                "location":{
                  "x":503,
                  "y":203},
                "size":{
                  "width":141,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "8fe874335b4448e1ba14374e21e47277":{
      "scriptId":"u0"},
    "2c8f80b85e6f49fea01f09ed7d8440ee":{
      "scriptId":"u1"},
    "9baec5c8e02a4a0fa1898ac58380b4a9":{
      "scriptId":"u2"},
    "a15277bc384a41e4bec0028ed1f8b495":{
      "scriptId":"u3"},
    "68512d91e1f449459977fef7a8bafdda":{
      "scriptId":"u4"},
    "26a5a73152ca4dbca89b2b5756003074":{
      "scriptId":"u5"},
    "a746150b4213452384fea6d28359bc27":{
      "scriptId":"u6"},
    "97c6ba8d681544a19e7fe83f7d77c682":{
      "scriptId":"u7"},
    "e95e67458c984f99bd2f3e1727f423ba":{
      "scriptId":"u8"},
    "01232e25300147debbd82e148b94124c":{
      "scriptId":"u9"},
    "c0d0b3a46d5645ab92b03f60032ac7f2":{
      "scriptId":"u10"},
    "9646d1c148d34cdd89ba1c1d30dd5380":{
      "scriptId":"u11"},
    "7f2a190367bd4ca6ac9f144d68960b7c":{
      "scriptId":"u12"},
    "875ec0b5dac1438986f284d95477f747":{
      "scriptId":"u13"},
    "a98874ee8c1344469690333207db33ff":{
      "scriptId":"u14"},
    "c658a45888354917b493112f2cf5ef3a":{
      "scriptId":"u15"},
    "3774bf2f76ef4b87a67e240dd66e83cb":{
      "scriptId":"u16"},
    "3363d544e75f420d8b77baaabc918eff":{
      "scriptId":"u17"},
    "0b5c145cd4fc455785f7367bd9fd3967":{
      "scriptId":"u18"},
    "8bd1d048cd454feeb02bea22baba0564":{
      "scriptId":"u19"},
    "21cdb275dcc641c09ce9dba524db8274":{
      "scriptId":"u20"},
    "b466d1f51ed142c7b5c395f52fd17075":{
      "scriptId":"u21"},
    "cd5f07227531459c930c0d3ad8123b5e":{
      "scriptId":"u22"},
    "16efb181c24645eab1471c7c78c7aa87":{
      "scriptId":"u23"},
    "fef3c4c8172c41e48020a8e95f7d52db":{
      "scriptId":"u24"},
    "fae53d88c1b94ba4ba45e4f977ece253":{
      "scriptId":"u25"},
    "94529e453179486dad8badb2329afc82":{
      "scriptId":"u26"},
    "b8053c8bb2084ac892550ae0d643bdf4":{
      "scriptId":"u27"},
    "a0e364d2f75442f583be2c7d566900b5":{
      "scriptId":"u28"},
    "a6179b13646f460f8c416b8ffd1edb47":{
      "scriptId":"u29"},
    "9d6291ca4adb4bf8839f2a06bc048d2e":{
      "scriptId":"u30"},
    "e6a73859b9834306a4edf805914b6624":{
      "scriptId":"u31"},
    "6fc5b4b0325d4ea9b379da1b288d7455":{
      "scriptId":"u32"},
    "de1f0cac9ab04465a9e31ec89c98e068":{
      "scriptId":"u33"},
    "c27f246b5c6342938ebf5a2a5775f50f":{
      "scriptId":"u34"},
    "0c3854de3f774f43adb7ed5a68463e92":{
      "scriptId":"u35"},
    "db2487428a434dd188b6a03cc844cfa7":{
      "scriptId":"u36"},
    "15ada4ef4e8f423eb206a1f523763bbb":{
      "scriptId":"u37"},
    "28e34d836e894efb8d85d5a04aa56c95":{
      "scriptId":"u38"},
    "61d8a895ba4349e49160300ae1f8f0f3":{
      "scriptId":"u39"},
    "4a672d1f84104b96beb345aea52202de":{
      "scriptId":"u40"}}});