$axure.loadCurrentPage({
  "url":"引导页面_-_1.html",
  "generationDate":new Date(1414911756813.21),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cead44a283314e02b1c066d59c8d66f9",
    "type":"Axure:Page",
    "name":"引导页面 - 1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"aa7bcbf2f06849149038ca6996bb02fb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":720,
              "height":1280}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3def29741e3945cbb6bf6f25c2efe3c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":720,
                  "height":1280}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/引导页面_-_1/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "aa7bcbf2f06849149038ca6996bb02fb":{
      "scriptId":"u0"},
    "3def29741e3945cbb6bf6f25c2efe3c1":{
      "scriptId":"u1"}}});